In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 1000)

In [3]:
# orders_qu.csv
url = "https://drive.google.com/file/d/1kvYPlqcaKuBpHStyaNSchBYIb2iTuEji/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orders = pd.read_csv(path)

# orderlines_qu.csv
url = "https://drive.google.com/file/d/1krfmZrcb92ZYPXu32fD6i6OA-_LQpVfo/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines = pd.read_csv(path)

# brands_cl.csv
url = "https://drive.google.com/file/d/1XGyabaa4mAkjixMk3XPgx_14OoSse3rs/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
brands = pd.read_csv(path)

# products_cl.csv
url = "https://drive.google.com/file/d/1IPnKYLSnrST0HBZMeSeNrhFfWU31QvwB/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products = pd.read_csv(path)

In [4]:
orders_df = orders.copy()
orderlines_df = orderlines.copy()
brands_df = brands.copy()
products_df = products.copy()

In [5]:
brands_df

    short              long
0     8MO         8Mobility
1     ACM              Acme
2     ADN            Adonit
3     AII             Aiino
4     AKI            Akitio
5     ALL         Allocacoc
6     AP2             Apple
7     APP             Apple
8     BAN        Band&Strap
9     BEA             Beats
10    BEL            Belkin
11    BEZ             Be.ez
12    BLL        BlueLounge
13    BLM  Blue Microphones
14    BNQ              BenQ
15    BOD        BodyGuardz
16    BOO              Booq
17    BOS              Bose
18    BTC         Boostcase
19    CAD              Bose
20    CAI          Casetify
21    CEL             Celly
22    COG            Cogito
23    CRU           Crucial
24    CYB        Cyberpower
25    CYG           Cygnett
26    DEV            Devolo
27    DJI               DJI
28    DLK            D-Link
29    DLL              Dell
30    DOD          Dodocool
31    DRO             Drobo
32    DVI             Devia
33    EIZ              Eizo
34    ELA             Elago
35    ELE     Elevation Lab
36    ELG            Elgato
37    ENV           Unknown
38    EVU            Evutec
39    FCM               FCM
40    FIB            Fibaro
41    FIF        FiftyThree
42    FIT            Fitbit
43    GAM          Gamevice
44    GLY        Glyph Atom
45    GOP             GoPro
46    GRT           Griffin
47    GTE      G-Technology
48    HAR     Harman Kardon
49    HGD       Henge Docks
50    HGS   HGST Travelstar
51    HIC           Hitcase
52    HOC         Hoco Nike
53    HOW         Honeywell
54    HTE       Hyper Pearl
55    IAM              I AM
56    ICA            Incase
57    IFR            iFrogz
58    IFX            iFixit
59    IHE           iHealth
60    IKM     IK Multimedia
61    IOT            iOttie
62    JAB             Jabra
63    JAW           Jawbone
64    JBL               JBL
65    JMO       Just Mobile
66    JOB              Joby
67    JYB           Jaybird
68    KAI       Kaiser Baas
69    KAN             Kanex
70    KEN        Kensington
71    KEU     Kenu Airframe
72    KIN          Kingston
73    KOO           Koogeek
74    KUA          Kukaclip
75    LAC             LaCie
76    LAN       LandingZone
77    LEE              Leef
78    LEX             Lexar
79    LGE                LG
80    LIB           Unknown
81    LIF         Lifeproof
82    LMP               LMP
83    LOG          Logitech
84    LUN           Lunatik
85    MAC           Macally
86    MAK          Maclocks
87    MAT            Matias
88    MBI      Mobility Lab
89    MDT       Mediterrans
90    MIC         Microsoft
91    MIN          Minibatt
92    MMW             My MW
93    MOL         Moleskine
94    MOP            Mophie
95    MOS             Moshi
96    MOX             Moxie
97    MTF           Mistify
98    MUJ             Mujjo
99    MUV             Muvit
100   MYF             MyFox
101   NDA             Nonda
102   NDE             Ndevr
103   NEA           Netatmo
104   NES              Nest
105   NIE           Ninebot
106   NIM            Nimbus
107   NKI             Nokia
108   NOD             Nodon
109   NOK              Noke
110   NOM             Nomad
111   NTE         NewerTech
112   OBL            Oblumi
113   OLI            Olixar
114   OLL          Olloclip
115   OPU            Opulus
116   OSM              Osmo
117   OTR          Startech
118   OTT          Otterbox
119   OWC               OWC
120   PAC              Pack
121   PAR            Parrot
122   PEB            Pebble
123   PHI           Philips
124   PIE       Replacement
125   PLA       Plantronics
126   POL          Polaroid
127   PQI               Pqi
128   PRO           Promise
129   PRY             Prynt
130   PUR              Puro
131   QAR            Qardio
132   QDO              QDos
133   QNA              QNAP
134   RAI       Rain Design
135   REP            Repair
136   RET     Retrak Utopia
137   RUT        Runstastic
138   RYV             Ryval
139   SAM           Samsung
140   SAN           SanDisk
141   SAT           Satechi
142   SDE           SDesign
143   SEA           Seagate
144   SEV           Service
145   SHE        SwitchEasy
146   SNA              Sena
147   SNN            Sonnet
148   SNS             Sonos
149   SOF          Software
150   SPE      Spek SeeThru
151   SPH            Sphero
152   SSE            Sen.se
153   STA          Startech
154   STC           Stacked
155   STI         Stil Mind
156   STK            Stikgo
157   STM               STM
158   SXA      SecurityXtra
159   SYN          Synology
160   TAD              Tado
161   TAM           Tangram
162   TCH            Tech21
163   THU             Thule
164   TIG             Tigra
165   TIL              Tile
166   TOS           Toshiba
167   TPL           TP-Link
168   TRA          Trascend
169   TRI             Tribe
170   TRK            TrackR
171   TRN      Trunk Sleeve
172   TUC            Tucano
173   TWS      Twelve South
174   UAG  Urban Armor Gear
175   WAC             Wacom
176   WDT   Western Digital
177   WHO            Whoosh
178   WIK           Wikango
179   WIT          Withings
180   WOE            Wowewa
181   XDO           X-Doria
182   XOO            Xoopar
183   XRI            X-Rite
184   XTO             Xtorm
185   ZAG          ZaggKeys
186   ZEP              Zepp

In [6]:
brands_df.isna().sum()

short    0
long     0
dtype: int64

In [7]:
brands_df.duplicated().sum()

np.int64(0)

In [8]:
brands_df["short"].duplicated().sum()

np.int64(0)

In [9]:
brands_df["long"].duplicated().sum()

np.int64(4)

In [10]:
brands_df.loc[(brands_df["long"].duplicated())]

    short      long
7     APP     Apple
19    CAD      Bose
80    LIB   Unknown
153   STA  Startech

In [11]:
brands_df.loc[(brands_df["long"].duplicated(keep=False))].sort_values(by="long")

    short      long
6     AP2     Apple
7     APP     Apple
17    BOS      Bose
19    CAD      Bose
117   OTR  Startech
153   STA  Startech
37    ENV   Unknown
80    LIB   Unknown

In [12]:
products_df.head()

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,34.99,1,1364

In [13]:
products_df["sku"].str[:3].head()

0    RAI
1    APP
2    APP
3    APP
4    KIN
Name: sku, dtype: object

In [14]:
products_df.loc[: , ["short"]] = products_df["sku"].str[:3]
products_df.head()

,sku,name,desc,price,in_stock,type,short
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,RAI
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,APP
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,APP
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,APP
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,34.99,1,1364,KIN

In [15]:
pbm = products_df.merge(brands_df, on="short", how="left")
pbm.head()

,sku,name,desc,price,in_stock,type,short,long
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,RAI,Rain Design
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,APP,Apple
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,APP,Apple
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,APP,Apple
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,34.99,1,1364,KIN,Kingston

In [16]:
brands_df.loc[(brands_df["long"].duplicated(keep=False))].sort_values(by="long")

    short      long
6     AP2     Apple
7     APP     Apple
17    BOS      Bose
19    CAD      Bose
117   OTR  Startech
153   STA  Startech
37    ENV   Unknown
80    LIB   Unknown

In [17]:
pbm.loc[pbm["short"] == "APP", :].shape[0]

1721

In [18]:
pbm.loc[pbm["short"] == "AP2", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
1172,AP20102,Second hand - Apple iPad Smart Cover Case Air Amarillo,Leather Case for iPad Air used (like new),45.00,0,12635403,AP2,Apple
2964,AP20104,Second hand - Apple iPad Case Silicone Case Mini 4 Rosa,used protective case ultrafine silicone cases mini 4,69.00,0,12635403,AP2,Apple
2965,AP20105,Like new - Apple iPad Case Silicone Case Mini 4 Lavender,used protective case ultrafine silicone cases mini 4,69.00,0,12635403,AP2,Apple
2980,AP20147,Like new - Apple TV 32GB media player,Refurbished Apple multimedia player,179.00,0,4259,AP2,Apple
4051,AP20111,"Like new - Apple iPad Smart Cover Pro 97 ""Midnight Blue",Second hand Case iPad Pro 97-inch,79.00,0,12635403,AP2,Apple
4052,AP20106,"Like new - Apple iPad Smart Cover Pro 97 ""Red",Smart case with different positions for 97 inches cases Pro,59.00,0,12635403,AP2,Apple
4055,AP20107,"Like new - Real Apple Smart Cover iPad Pro 97 ""Blue",Case used with different positions for 97 inches cases Pro,59.00,0,12635403,AP2,Apple
4059,AP20110,"Second hand - Apple iPad Silicone Case Pro 97 ""Red",Silicone light cover and soft touch for iPad Pro 97-inch.,79.00,0,12635403,AP2,Apple
4061,AP20109,"Second hand - Apple iPad Silicone Case Pro 97 ""Light Pink",Case silicone used light and soft touch for iPad Pro 97-inch,79.00,0,12635403,AP2,Apple
4212,AP20101,Like new - Apple iPad mini Smart Cover 4 Blue Real,Reconditioned Smart Cover iPad mini 4 Blue Real,45.00,1,12635403,AP2,Apple
6710,AP20021,"Second hand - Apple iMac 215 ""Core i5 Quad-Core 27GHz | 8GB RAM | 1TB HDD | Late 2012 (MD093LL / A)",IMac used i5 215 inch quad-core 27GHz | 8GB RAM | 1TB HDD | Late 2012 (MD093LL / A),879.00,0,1282,AP2,Apple
6715,AP20023,"Second hand - Apple iMac 215 ""Core i5 Quad-Core 27GHz | 8GB RAM | 1TB HDD | Late 2013 (ME086Y / A)",IMac used i5 215 inch quad-core 27GHz | 8GB RAM | 1TB HDD | Late 2013 (ME086Y / A),939.00,0,1282,AP2,Apple
6716,AP20025,"Second hand - Apple iMac 215 ""Core i5 Quad-Core 14GHz | 8GB RAM | 500GB HDD",IMac reconditioned 215 inch quad-core i5 14GHz | 8GB RAM | 500GB HDD,1279.00,0,1282,AP2,Apple
6719,AP20028,"Like new - Apple iMac 215 ""Core i5 Quad-Core 16GHz | 8GB RAM | 1TB HDD",IMac reconditioned 215 inch quad-core i5 16GHz,1279.00,1,1282,AP2,Apple
7051,AP20085,"Like new - Apple Macbook Air 13 ""i5 16GHz | 8GB RAM | 256GB Flash",Computer Refurbished MacBook Air 13-inch i5 16GHz | 8GB RAM | 256GB Flash,1349.00,0,"2,17E+11",AP2,Apple
7052,AP20079,"Like new - Apple MacBook Pro Retina 13 ""i5 27 GHz | 8GB RAM | 128GB Flash",Computer Refurbished MacBook Pro 13-inch i5 27GHz | 8GB RAM | 128GB Flash,1499.00,0,"2,17E+11",AP2,Apple
7054,AP20080,"Open - Apple MacBook Retina 12 ""Core M 11 GHz | 8GB RAM | 256GB Flash | Silver",Computer Refurbished MacBook 12-inch Core M 11GHz | 8GB RAM | 256GB Flash,1449.00,0,"5,39E+11",AP2,Apple
7056,AP20081,"Like new - Apple MacBook Pro Retina 15 ""i7 22 GHz | RAM 16GB | 256GB Flash",Computer MacBook Pro 15 inch i7 refitted 22GHz | 16GB RAM | 256GB Flash,2249.00,0,"2,17E+11",AP2,Apple
7057,AP20083,"Like new - Apple MacBook Retina 12 ""Core m3 11GHz | 8GB RAM | 256GB Flash | Space Gray",Computer Refurbished MacBook 12-inch Core m3 11GHz | 8GB RAM | 256GB Flash,1449.00,0,"5,39E+11",AP2,Apple
7058,AP20084,"Like new - Apple Macbook Air 13 ""i5 16GHz | 8GB RAM | 128GB Flash",Computer Refurbished MacBook Air 13-inch i5 16GHz | 8GB RAM | 128GB Flash,1099.00,0,"2,17E+11",AP2,Apple
7079,AP20016,"Second hand - Apple iMac 215 ""Core i5 Quad-Core 25GHz | 8GB RAM | 500GB HDD",IMac used i5 215 inch quad-core 25GHz | 8GB RAM | 500GB HDD,1199.00,0,1282,AP2,Apple
7082,AP20093,"Like new - Apple iPad Pro 9.7 ""Wi-Fi 32GB Space Gray",9.7-inch iPad Pro Refurbished 32GB Space Gray,679.00,0,51871714,AP2,Apple
7083,AP20094,"Open - Apple iPad Pro 9.7 ""Wi-Fi + Cellular 128GB Gold",iPad Pro 128GB 9.7 inch Color refitted Gold,939.00,0,51871714,AP2,Apple
7084,AP20089,Open - Apple iPad mini 2 Wi-Fi 16GB Silver,iPad Mini 2 16GB Color Silver Reconditioned,289.00,0,12031714,AP2,Apple
7085,AP20096,"Second hand - Apple iPad Pro 12.9 ""Wi-Fi 128GB Silver",iPad Pro 12.9 inch Wi-Fi refurbished 128GB Silver,1009.00,0,51861714,AP2,Apple
7086,AP20097,"Like new - Apple iPad Pro 12.9 ""Wi-Fi 128GB Space Gray",iPad Pro 12.9 inch Wi-Fi 128GB Reconditioned Gray Space,1009.00,0,51861714,AP2,Apple
7087,AP20098,"Like new - Apple iPad Pro 12.9 ""Wi-Fi 32GB Silver",Pro 12.9 inch iPad Wi-Fi 32GB Silver Reconditioned,899.00,0,51861714,AP2,Apple
7088,AP20099,"Second hand - Apple iPad Pro 12.9 ""Wi-Fi 32GB Space Gray",Pro 12.9 inch iPad Wi-Fi 32GB Space Gray Refurbished,899.00,0,51861714,AP2,Apple
7089,AP20113,Like new - Apple Pencil,Refurbished Apple iPad Pencil Pro,109.00,0,1229,AP2,Apple
7090,AP20090,Second hand - Apple iPad Mini 2 Wi-Fi 16GB Space Gray,Reconditioned Apple iPad Mini 2 16GB Space Gray,289.00,0,12031714,AP2,Apple
7091,AP20091,Like new - Apple iPad mini 2 Wi-Fi 32GB Space Gray,iPad Mini 2 32GB Space Gray Refurbished,289.00,0,12031714,AP2,Apple
7092,AP20087,Open - Apple iPad Air Wi-Fi 16GB Silver,Reconditioned Air iPad Wi-Fi 16GB Silver,389.00,0,12051714,AP2,Apple
7093,AP20088,Second hand - Apple iPad 16GB Wi-Fi Air Space Gray,Air refurbished iPad Wi-Fi 16GB Space Gray,389.00,0,12051714,AP2,Apple
7094,AP20092,Open - Apple iPad mini Wi-Fi 16GB Space Gray,Reconditioned Apple iPad mini 16GB Space Gray,239.00,0,13621714,AP2,Apple
7109,AP20160,Excellent - Apple Mac mini Core i5 26GHz | 1TB HDD | 8GB RAM,Computer Core i5 Mac mini reconditioned | 8GB RAM | 1TB HDD,799.00,0,1282,AP2,Apple
7110,AP20100,Like new - Apple Smart Cover iPad Mini 4 Stone,Polyurethane sheath reconditioned for cases mini 4,45.00,1,12635403,AP2,Apple
7113,AP20108,Like new - Apple iPad Smart Cover Case Mini / Retina Black,Smart leather case for your iPad Mini (Refurbished),79.00,0,12635403,AP2,Apple
7115,AP20146,Like new - Apple TV 64GB media player,Refurbished Apple multimedia player,229.00,0,4259,AP2,Apple
7116,AP20148,Like new - Apple TV 3 media player,Refurbished Apple multimedia player,79.00,0,4259,AP2,Apple
7117,AP20159,Like new - Apple Mac mini Core i5 14GHz | 4GB RAM | 500GB HDD,Computer Core i5 Mac mini refitted 14GHz | 4GB RAM | 500GB HDD,555.49,0,"5,44E+11",AP2,Apple
7118,AP20156,"Like new - Apple iMac 21.5 ""Core i5 31GHz 4K Retina | 8GB RAM | 1TB HDD",Computer Refurbished iMac 21.5-inch 4K Retina Core i5 31GHz | 8GB RAM | 1TB HDD,1729.00,0,1282,AP2,Apple
7119,AP20157,"Like new - Apple iMac 27 ""Core i5 Retina 5K 32GHz | 8GB RAM | 1TB HDD | Late 2015",Computer Refurbished iMac 27 inch Core i5 32GHz | 8GB RAM | 1TB HDD,2129.00,0,51882158,AP2,Apple
7120,AP20392,"Like new - Apple iMac 27 ""Core i7 Retina 5K 4Ghz | 16GB RAM | Flash 512GB | Radeon R9 M395X 4GB",Refurbished iMac 27-inch Retina 5K | Core i7 4Ghz | Flash 512GB | 16GB | Radeon R9 M395X 4GB,3709.00,0,51882158,AP2,Apple
7121,AP20155,"Like new - Apple iMac Retina 215 ""Quad-core i5 28GHz | 8GB RAM | 1TB HDD",IMac reconditioned 215 inch Retina Quad-core i5 28GHz 8GB RAM and HDD 1TB,1529.00,0,1282,AP2,Apple
7126,AP20103,Like new - Apple iPhone 64GB Space Gray,Apple iPhone SE Free Refurbished 64GB Space Gray,549.00,0,51601716,AP2,Apple
7127,AP20132,Like new - Apple iPhone 64GB Silver,Apple iPhone SE Free Refurbished 64GB Color Silver,549.00,0,51601716,AP2,Apple
7128,AP20163,Like new - Apple iPhone 64GB Rose Gold,Refurbished Apple iPhone 64GB Free Rose Gold Color,549.00,0,51601716,AP2,Apple
7129,AP20165,Like new - Apple iPhone 16GB Space Gray,Apple iPhone SE Free Refurbished 16GB Space Gray,489.00,0,51601716,AP2,Apple
7130,AP20177,Like new - Apple iPhone 7 128GB Gold Rosa,Refurbished Apple iPhone 7 Free 128GB Rose Gold Color,749.00,0,85641716,AP2,Apple
7131,AP20166,Like new - Apple iPhone 16GB Gold,Apple iPhone SE Free Refurbished 16GB Color Gold,489.00,0,51601716,AP2,Apple
7132,AP20167,Like new - Apple iPhone 7 Plus 32GB Black,Apple iPhone 7 Plus Free Refurbished 32GB Color Black,779.00,0,85651716,AP2,Apple
7133,AP20169,Like new - Apple iPhone 7 Plus 128GB Rose Gold,Apple iPhone 7 Plus Free Refurbished 128GB Rose Gold Color,889.00,0,85651716,AP2,Apple
7134,AP20178,Like new - Apple iPhone 7 128GB Black Bright,Apple iPhone 7 Free Refurbished 128GB Color Black Bright,749.00,0,85641716,AP2,Apple
7135,AP20170,Like new - Apple iPhone 7 Plus 128GB Black,Apple iPhone 7 Plus Free Refurbished 128 GB Color Black,889.00,0,85651716,AP2,Apple
7136,AP20179,Second hand - Apple iPhone 7 128GB Gold,Apple iPhone 7 Free Refurbished 128GB Color Gold,749.00,1,85641716,AP2,Apple
7137,AP20189,Open - Apple iPhone 5s 16GB Space Gray,Refurbished Apple iPhone 5s 16GB Free Color Gray Space,409.00,0,51601716,AP2,Apple
7138,AP20180,Like new - Apple iPhone 7 128GB Black,Free Apple iPhone 7 refitted 128GB Color Black Bright,749.00,0,85641716,AP2,Apple
7139,AP20190,Open - Apple iPhone 5S 16GB Silver,Apple iPhone 5s 16GB refitted Free Color Silver,409.00,0,51601716,AP2,Apple
7140,AP20182,Like new - Apple iPhone 6s Plus 32GB Silver,Apple iPhone 6s Plus Free Refurbished 32GB Color Silver,639.00,0,24811716,AP2,Apple
7141,AP20171,Like new - Apple iPhone 7 32GB Silver,Apple iPhone 7 Free Refurbished 32GB Color Silver,639.00,0,85641716,AP2,Apple
7142,AP20183,Like new - Apple iPhone 6s Plus 128GB Gold,Apple iPhone 6s Plus 128GB Reconditioned Free Color Gold,749.00,0,24811716,AP2,Apple
7143,AP20173,Like new - Apple iPhone 32GB Rose Gold 7,Apple iPhone 7 Free Refurbished 32GB Rose Gold Color,639.00,0,85641716,AP2,Apple
7144,AP20174,Like new - Apple iPhone 7 32GB Black,Apple iPhone 7 Free Refurbished 32GB Color Black,639.00,0,85641716,AP2,Apple
7145,AP20175,Like new - Apple iPhone 7 256GB Gold,Apple iPhone 7 Free Refurbished 256GB Color Gold,990.33,0,85641716,AP2,Apple
7146,AP20176,Open - Apple iPhone 7 256GB Black,Apple iPhone 7 Free Refurbished 256 GB Color Black,989.00,0,85641716,AP2,Apple
7147,AP20184,Like new - Apple iPhone 6s 32GB Space Gray,Apple iPhone 6s Refurbished 32GB Free Space Gray,529.00,0,24821716,AP2,Apple
7148,AP20144,Excellent - Apple AirPort Time Capsule 2TB,Apple AirPort Time Capsule 2TB reconditioned,329.00,0,11935397,AP2,Apple
7149,AP20185,Like new - Apple iPhone 6s 32GB Silver,Apple iPhone 6s Free Refurbished 32GB Color Silver,529.00,0,24821716,AP2,Apple
7150,AP20145,Like new - Apple AirPort Time Capsule 3TB,Apple Airport Time Capsule 3TB Reconditioned,429.00,0,11935397,AP2,Apple
7151,AP20186,Like new - Apple iPhone 32GB Rose Gold 6s,Apple iPhone 6s Refurbished 32GB Free Rose Gold Color,529.00,0,24821716,AP2,Apple
7152,AP20149,Like new - Apple AirPort Express Base Station,Apple Airport Express Base Station Reconditioned,109.00,1,1334,AP2,Apple
7153,AP20187,Like new - Apple iPhone 16GB Rose Gold 6s,Apple iPhone 6s Refurbished 16GB Free Rose Gold Color,749.00,0,24821716,AP2,Apple
7154,AP20150,Like new - Apple Airport Extreme,Apple Airport Extreme Base Station 802.11ac reconditioned,219.00,0,1334,AP2,Apple
7155,AP20193,Open - Apple iPhone 6s Plus 64GB Space Gray,Apple iPhone 6s Plus Free Refurbished 64GB Space Gray,969.00,0,24811716,AP2,Apple
7156,AP20191,"Open - Apple iPad Pro 9.7 ""32GB Wi-Fi Plata",9.7-inch iPad Pro Refurbished 32GB Silver,679.00,0,51871714,AP2,Apple
7157,AP20194,Like new - Apple iPhone 6s 64GB Silver,Apple iPhone 6s Free Refurbished 64GB Color Silver,859.00,0,24821716,AP2,Apple
7158,AP20188,Like new - Apple iPhone 6 Plus 16GB Space Gray,Apple iPhone 6 Plus Free Refurbished 16GB Space Gray,749.00,0,21571716,AP2,Apple
7159,AP20112,Second hand - Apple Smart Case iPad Air Case PRODUCT (RED),protective cover Smart Case for iPad Air secondhand,79.00,0,12635403,AP2,Apple
7160,AP20154,Like new - Apple Wireless Keyboard,Spanish Keyboard Mac and iPad Ultrathin Bluetooth reconditioned,79.00,0,13855401,AP2,Apple
7161,AP20152,Like new - Apple Magic Trackpad,Bluetooth Apple Wireless Trackpad refurbished (like new),79.00,0,1387,AP2,Apple
7162,AP20114,"Like new - Apple Smart Keyboard Keyboard Folio iPad Pro 12.9 """,In Spanish and cover with keyboard shortcuts (refurbished) for iPad Pro 12.9,189.00,0,12575403,AP2,Apple
7163,AP20115,"Like new - Apple Smart Keyboard Pro Keyboard Folio iPad 9.7 """,Reconditioned cover with keyboard shortcuts and Spanish (direct connection) for iPad Pro 97,169.00,0,12575403,AP2,Apple
7164,AP20151,Like new - Apple USB SuperDrive (June 2012 Model),CD / DVD Refurbished MacBook Pro Retina MacBook Air iMac Mac Pro and Mac Mini,89.00,0,1424,AP2,Apple
7165,AP20116,Like new - Apple iPhone Silicone Case 6 / 6s Plus Charcoal Gray,Reconditioned silicone sleeve microfiber premium for iPhone 6 / 6S,45.00,1,11865403,AP2,Apple
7166,AP20143,Like new - Apple DVI to HDMI Adapter,HDMI adapter DVI second hand for Mac,35.00,0,1230,AP2,Apple
7167,AP20117,Like new - Apple iPhone Silicone Case 6 / 6s Plus Blue Night,Reconditioned silicone sleeve microfiber premium for iPhone 6 Plus / 6s Plus,45.00,1,11865403,AP2,Apple
7168,AP20142,Second hand - Apple USB-C to Multiport VGA,Reconditioned USB-C adapter to VGA for MacBook,79.00,0,12585395,AP2,Apple
7169,AP20119,Second hand - Apple Leather Case iPhone 6 / 6S Candy brown,Reconditioned sleeve leather and microfiber premium for iPhone 6 / 6S,55.00,0,11865403,AP2,Apple
7170,AP20141,Second hand - Apple USB-C Multiport Digital AV Adapter,Reconditioned USB adapter to HDMI-C high-resolution MacBook,79.00,0,12585395,AP2,Apple
7171,AP20120,Like new - Apple Leather Case iPhone 6 / 6S brown Plus,Reconditioned sleeve leather and microfiber premium for iPhone 6 Plus / 6s Plus.,49.00,0,11865403,AP2,Apple
7172,AP20121,Second hand - Smart Battery Apple iPhone Battery Case 7 Blanco,Reconditioned Case with battery for iPhone Resale 7,119.00,1,"5,49E+11",AP2,Apple
7173,AP20122,Like new - Apple Mini DisplayPort to DVI Adapter,Refurbished adapter mini DisplayPort to DVI MacBook and MacBook Pro (Unibody),35.00,1,12585395,AP2,Apple
7174,AP20123,Second hand - Apple Mini DisplayPort to VGA Adapter,Reconditioned adapter mini Display Port to VGA MacBook and MacBook Pro (Unibody),35.00,0,1325,AP2,Apple
7184,AP20127,Second hand - Apple Lightning to VGA Adapter,Apple Lightning Adapter refitted with a VGA connector,59.00,0,14365395,AP2,Apple
7185,AP20126,Like new - Apple Lightning to USB adapter for cameras,Apple Lightning Adapter refitted with a USB connector for cameras,35.00,0,12585395,AP2,Apple
7186,AP20128,Like new - Adapter Apple Lightning to SD Card Reader,Reconditioned adapter connector Lightning to SD Card Reader,35.00,0,14365395,AP2,Apple
7187,AP20129,Like new - Apple Lightning to USB 3.0 Adapter,Lightning connector adapter to USB 3.0,45.00,0,14365395,AP2,Apple
7188,AP20130,Like new - Apple Lightning to USB Cable 1m-C,Reconditioned Apple USB Cable Connection Lightning-C 1m for iPhone iPad and iPod,29.00,1,1230,AP2,Apple
7189,AP20131,Like new - Apple Lightning to USB Cable 2m-C,Apple Lightning Cable refitted with free USB-C 2 m for iPhone iPad and iPod,39.00,0,1230,AP2,Apple
7190,AP20134,Second hand - Apple MagSafe to MagSafe converter 2,Converter Apple MagSafe connector refitted to MagSafe 2.,12.00,0,12585395,AP2,Apple
7191,AP20135,Like new - Apple 85W MagSafe 2 charger MacBook Pro Retina display,Power charger reacondicioando MagSafe 2 of 85 W for Macbooks Retina 15 inches and 17 inches,89.00,0,13005399,AP2,Apple
7216,AP20136,Second hand - Apple Travel Adapter Kit,Adapter kit with seven types of interchangeable plugs,35.00,0,12585395,AP2,Apple
7217,AP20137,Like new - Apple Thunderbolt Cable 2m White,Cable refitted with Thunderbolt connection 2m for Mac,45.00,0,12585395,AP2,Apple
7218,AP20138,Like new - Apple Thunderbolt Cable 0.5m White,Thunderbolt Cable 0.5m refitted for Mac,35.00,0,12585395,AP2,Apple
7782,AP20214,Open - Apple Watch Sport 38mm Aluminum Case Space Gray and Black Belt Sport,Apple Watch Sport Aluminum Space Gray 38mm black sports refitted with belt,419.00,0,24885185,AP2,Apple
7783,AP20217,Open - Apple Watch Sport Stone Rose Gold 42mm Strap,Apple Watch Sport Aluminum Rose Gold 42mm Strap refitted with sports Stone,419.00,0,24895185,AP2,Apple
7784,AP20219,Open - Apple Watch Series 1 42mm Aluminum Gold Case and Strap Sports Cacao,Apple Watch Gold Series 1 Aluminum 42mm refitted with sports cocoa belt,369.00,0,24895185,AP2,Apple
7785,AP20221,Like new - Apple Watch Nike + 42mm Aluminum Case and Space Gray Nike Sport Strap Black / Volt,Apple Watch 42 mm refitted with double waterproof GPS processor core and belt 50mts exclusive Nike +,469.00,0,24895185,AP2,Apple
7790,AP20197,Like new - Apple Dock to USB Cable iPhone iPad and iPod White Compatible Apple,Cable iPhone iPad and iPod dock USB refitted.,25.00,0,1230,AP2,Apple
7791,AP20198,Like new - Apple Siri Remote,Remote refitted to the Media Player Apple Apple TV.,89.00,0,54864259,AP2,Apple
7792,AP20199,Like new - Apple Smart Battery Battery Case iPhone 6s Charcoal Gray,Reconditioned Battery Case for iPhone 6s and 6,119.00,0,"5,49E+11",AP2,Apple
7793,AP20200,Like new - Apple Leather Case Cover iPhone 6 Plus / 6s Plus Black,Reconditioned ultrathin leather case and microfiber premium for iPhone 6 Plus / 6s Plus.,59.00,0,11865403,AP2,Apple
7794,AP20201,Like new - Apple Case iPhone 6 Plus / 6s Plus Silicone Case White,Reconditioned ultrathin silicone cover and microfiber premium for iPhone 6 Plus / 6s Plus.,45.00,0,11865403,AP2,Apple
7795,AP20202,Like new - Apple Leather Case Cover iPhone 6 / 6s Blue Night,Reconditioned ultrathin leather case and microfiber premium for iPhone 6 / 6S,55.00,0,11865403,AP2,Apple
7796,AP20205,Second hand - Apple iPhone Silicone Case Cover 7 Plus Blue Night,Reconditioned ultrathin silicone case and microfiber premium for iPhone 7 Plus,45.00,0,11865403,AP2,Apple
7797,AP20206,Like new - Apple iPhone Silicone Case Cover 7 Red Plus,Reconditioned ultrathin silicone case and microfiber premium for iPhone 7 Plus,45.00,0,11865403,AP2,Apple
7798,AP20207,Like new - Apple Leather Case 7 Brown Candy iPhone Case,Reconditioned ultrathin leather case and microfiber premium for iPhone 7,55.00,0,11865403,AP2,Apple
7799,AP20208,Second hand - Apple Leather Case Cover iPhone 7 Plus Blue Night,Reconditioned ultrathin leather case and microfiber premium for iPhone 7 Plus,59.00,0,11865403,AP2,Apple
7800,AP20209,Like new - Apple Leather Case Cover Black iPhone 7 Plus,Reconditioned ultrathin leather case and microfiber premium for iPhone 7 Plus,59.00,0,11865403,AP2,Apple
7801,AP20210,Like new - Apple iPhone Leather Case Cover 7 Red Plus,Reconditioned ultrathin leather case and microfiber premium for iPhone 7 Plus,59.00,0,11865403,AP2,Apple
7802,AP20213,Like new - Apple iPad Case Silicone Case Mini 4 Stone,reconditioned protective sheath ultrafine iPad 4 mini silicone.,69.00,1,12635403,AP2,Apple
7803,AP20211,Like new - Apple iPad mini Smart Cover Black,Reconditioned Smart Case for iPad mini polyurethane,45.00,0,1298,AP2,Apple
7804,AP20212,"Like new - Apple iPad Silicone Case Pro 129 ""Charcoal Gray",Reconditioned sleeve lightweight silicone and soft touch for iPad Pro 129 inches,89.00,0,1298,AP2,Apple
7805,AP20203,Second hand - Apple Leather Case Cover iPhone 6 / 6S PRODUCT (RED),Reconditioned ultrathin leather case and microfiber premium for iPhone 6 / 6S.,55.00,0,11865403,AP2,Apple
7806,AP20215,Like new - magnetic charging cable for Apple Watch (2m),Magnetic charging cable for Apple Watch reconditioned,45.00,0,1298,AP2,Apple
7807,AP20218,Like new - Apple Leather Strap 42mm Loop Midnight Blue Size M,Leather strap with grainy texture for Apple Watch 42 mm,159.00,0,1298,AP2,Apple
7886,AP20222,Like new - Apple iPad mini 2 Wi-Fi 32GB Silver,Refurbished iPad Mini 2 32GB Wi-Fi Plata,289.00,0,12031714,AP2,Apple
7887,AP20223,Like new - Apple iPad Air 2 Wi-Fi 64GB Silver,Refurbished Apple iPad Air 2 64GB Wi-Fi Plata,529.00,0,42931714,AP2,Apple
7888,AP20230,Like new - Apple iPad Air 2 Wi-Fi + Cellular 32GB Silver,Reconditioned Apple iPad Air 2 32GB Wi-Fi + Cellular Silver,549.00,0,42931714,AP2,Apple
7889,AP20224,Like new - Apple iPad 2 Wi-Fi Air 128GB Space Gray,Apple iPad Air 2 Refurbished 128GB Wi-Fi Gray Space,539.00,0,42931714,AP2,Apple

In [19]:
pbm.loc[pbm["short"] == "MUJ", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
336,MUJ0009,Mujjo Touchscreen Gloves iPhone iPad and iPod Gray (Size M / L),IPhone iPad and iPod gloves.,24.99,0,11905404,MUJ,Mujjo
924,MUJ0007,Mujjo Touchscreen Gloves iPhone iPad and iPod Black (Size S / M),Gloves iPhone iPad iPad 2 iPad 3 and iPod.,24.99,0,12285400,MUJ,Mujjo
5020,MUJ0012,Mujjo Leather Wallet Leather Case Tan iPhone 7/8,ultrathin cover with card case and material vegetable tanned leather for iPhone 7/8,39.90,0,11865403,MUJ,Mujjo
5021,MUJ0013,Mujjo Leather Wallet Case Black Leather iPhone 7,ultrathin cover with card case and material vegetable tanned leather for iPhone 7,39.90,0,11865403,MUJ,Mujjo
5022,MUJ0014,Mujjo Leather Wallet Leather Case iPhone 8/7 Gray,ultrathin cover with card case and material vegetable tanned leather for iPhone,39.90,0,11865403,MUJ,Mujjo
5023,MUJ0020,Mujjo Leather Wallet Case Black Leather iPhone 7 Plus,An ultra thin card case and material with vegetable tanned leather for iPhone 7 Plus,49.90,0,11865403,MUJ,Mujjo
5024,MUJ0021,Mujjo Leather Wallet Leather Case iPhone 8/7 Plus Gray,An ultra thin card case and material with vegetable tanned leather for iPhone 8/7 Plus,49.90,0,11865403,MUJ,Mujjo
5119,MUJ0024,Mujjo Leather Black Leather Case iPhone 7 Plus,ultrathin Case for iPhone vegetable tanned leather 7 Plus,44.90,0,11865403,MUJ,Mujjo
5140,MUJ0016,Mujjo Leather Case Tan Leather iPhone 8/7/6,ultrathin Case for iPhone vegetable tanned leather,39.90,0,11865403,MUJ,Mujjo
5143,MUJ0017,Mujjo Leather Black Leather Case iPhone 8/7/6,ultrathin cover with vegetable tanned leather material for iPhone,39.90,0,11865403,MUJ,Mujjo
5144,MUJ0023,Mujjo Leather Leather iPhone Case 8 Plus / 7 Plus Tan,ultrafine material cover with vegetable tanned leather for iPhone 8 Plus or 7-Plus,44.90,0,11865403,MUJ,Mujjo
5151,MUJ0019,Mujjo Leather Wallet Leather Case iPhone 8 Plus / 7 Plus Tan,Ultra Thin Case with card holder and vegetable tanned leather material for iPhone 7 Plus,49.90,0,11865403,MUJ,Mujjo
5433,MUJ0018,Mujjo iPhone Leather Case Leather Champagne 8/7/6,ultrathin Case for iPhone vegetable tanned leather 7,39.90,1,11865403,MUJ,Mujjo
5434,MUJ0025,Mujjo Leather Leather iPhone Case 8Plus / 7 Plus Champagne,ultrathin Case for iPhone vegetable tanned leather and 7 Plus 8 Plus,44.90,1,11865403,MUJ,Mujjo
5435,MUJ0015,Mujjo iPhone Leather Wallet Leather Case 7 Champagne,ultrathin cover with card case and material vegetable tanned leather for iPhone 7,39.90,1,11865403,MUJ,Mujjo
5436,MUJ0022,Mujjo Leather Wallet Leather Case iPhone 8 Plus / 7 Plus Champagne,ultrathin cover with card case and material vegetable tanned leather for iPhone 7 Plus,49.90,1,11865403,MUJ,Mujjo
6404,MUJ0031,Mujjo Single-Layered gloves color touch screen Black size M,M size gloves for touch screens.,29.95,1,11905404,MUJ,Mujjo
6408,MUJ0032,Mujjo Single-Layered gloves color touch screen Black size S,S size gloves for touch screens.,29.95,1,11905404,MUJ,Mujjo
6410,MUJ0026,"Mujjo MacBook Pro sleeve Sleeve 13 ""/ Air 13"" Black / Brown",Travel Case for MacBook Pro 13-inch MacBook Air 13 pulgadasen Color Black / Brown,69.90,1,13835403,MUJ,Mujjo
6411,MUJ0027,"Mujjo MacBook Pro sleeve Sleeve 13 ""/ Air 13"" Black",Travel Case for MacBook Pro 13-inch MacBook Air 13 pulgadasen Color Black.,69.90,1,13835403,MUJ,Mujjo
6412,MUJ0030,"Mujjo MacBook Pro Sleeve Case 15 ""Black",Travel Case for MacBook Pro format on 15-inch,74.90,1,13835403,MUJ,Mujjo
6413,MUJ0029,"Mujjo MacBook Pro Sleeve Case 15 ""Black / Brown",Travel Case for MacBook Pro 15-inch Black / Brown,74.90,1,13835403,MUJ,Mujjo
6414,MUJ0028,"Mujjo Folio Leather Case Sleeve Macbook Pro 13 ""/ Air 13"" brown",Leather Case for MacBook Pro 13-inch and 13-inch MacBook Air,99.90,0,13835403,MUJ,Mujjo
6935,MUJ0018-A,Open - Mujjo Leather Black Leather Case iPhone 7 Plus,ultrathin Case for iPhone vegetable tanned leather 7 Plus,44.90,0,1298,MUJ,Mujjo
8178,MUJ0033,Mujjo Full Leather Wallet Leather Case iPhone X Tan,An ultra thin with card and vegetable tanned leather material iPhone X,44.90,1,11865403,MUJ,Mujjo
8179,MUJ0035,Mujjo Full Leather Skin Case iPhone X Tan,Case ultrafine material vegetable tanned leather for iPhone X,49.90,1,11865403,MUJ,Mujjo
8180,MUJ0036,Mujjo Full Leather iPhone Case X Black Leather,ultrathin Case for iPhone vegetable tanned leather X,49.90,1,11865403,MUJ,Mujjo
8181,MUJ0037,Mujjo Full Leather Wallet Leather Case Tan iPhone 7/8,ultrathin cover with card case and material vegetable tanned leather for iPhone 8,44.90,1,11865403,MUJ,Mujjo
8182,MUJ0038,Mujjo Full Leather Wallet Leather Case Black iPhone 7/8,ultrathin cover with card case and material vegetable tanned leather for iPhone 7/8,44.90,1,11865403,MUJ,Mujjo
8183,MUJ0040,Mujjo Full Leather Skin Case Black iPhone 7/8,ultrathin cover with vegetable tanned leather material for iPhone 7/8,49.90,1,11865403,MUJ,Mujjo
8184,MUJ0041,Mujjo Full Leather Case iPhone Skin 8 Plus / 7 Plus Tan,Case ultrafine material vegetable tanned leather for iPhone 8 Plus,49.90,1,11865403,MUJ,Mujjo
8185,MUJ0042,Mujjo Full Leather Case iPhone Skin 8 Plus / 7 Black Plus,ultrathin Case for iPhone vegetable tanned leather 8 Plus / 7 Plus,49.90,1,11865403,MUJ,Mujjo
8186,MUJ0039,Mujjo Full Leather Skin Case Tan iPhone 7/8,ultrathin Case for iPhone vegetable tanned leather 7/8,49.90,1,11865403,MUJ,Mujjo
8190,MUJ0034,Mujjo Full Leather Wallet Case iPhone X Black Leather,An ultra thin card case and material with vegetable tanned leather iPhone X,44.90,1,11865403,MUJ,Mujjo
8880,MUJ0010-A,Open - Mujjo Leather Case Tan Leather iPhone 8/7/6,ultrathin Case for iPhone vegetable tanned leather with open packaging,39.90,0,11865403,MUJ,Mujjo
9411,MUJ0028-A,Open - Mujjo Full Leather Wallet Case iPhone X Black Leather,Case reconditioned ultrafine material with card case and vegetable tanned leather iPhone X,44.90,0,11865403,MUJ,Mujjo

In [20]:
brands_df.loc[brands_df["short"] == "MUJ", "long"] = "Mujjo"

In [21]:
brands_df.loc[brands_df["short"] == "MUJ", :]

   short   long
98   MUJ  Mujjo

In [22]:
pbm.loc[pbm["short"] == "MOP", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
25,MOP0011,Mophie Juice Pack Air Battery Case iPhone 4 / 4S black,Battery Case iPhone 4 / 4S rigid polymer.,69.99,0,"5,49E+11",MOP,Mophie
57,MOP0013,Mophie Juice Pack Air Battery Case iPhone 4 / 4S White,Case Battery (1500mAh) iPhone 4 / 4S polymer.,69.95,0,"5,49E+11",MOP,Mophie
360,MOP0027,Mophie Juice Pack Helium (1500mAh) battery cover iPhone SE / 5s / 5 gray,IPhone Battery Case SE / 5s / 5 plastic and metal.,79.99,0,"5,49E+11",MOP,Mophie
590,MOP0031,Mophie Juice Pack Helium (1500mAh) battery cover iPhone SE / 5s / 5 Blue,IPhone Battery Case SE / 5s / 5 plastic and metal.,79.99,0,"5,49E+11",MOP,Mophie
591,MOP0033,Mophie Juice Pack Helium (1500mAh) battery cover iPhone SE / 5s / 5 red,IPhone Battery Case SE / 5s / 5 plastic and metal.,79.99,0,"5,49E+11",MOP,Mophie
685,MOP0034,Mophie Juice Pack Air (1700mAh) iPhone Battery Case iPhone SE / 5s / 5 black,IPhone Battery Case SE / 5s / 5 plastic and metal.,99.95,0,"5,49E+11",MOP,Mophie
686,MOP0035,Mophie Juice Pack Air (1700mAh) battery cover iPhone SE / 5s / 5 white,IPhone Battery Case SE / 5s / 5 plastic and metal.,99.95,0,"5,49E+11",MOP,Mophie
687,MOP0036,Mophie Juice Pack Air (1700mAh) battery cover iPhone SE / 5s / 5 gold,IPhone Battery Case SE / 5s / 5 plastic and metal.,99.95,0,"5,49E+11",MOP,Mophie
688,MOP0037,Mophie Juice Pack Plus (2100mAh) battery cover iPhone SE / 5s / 5 Black,IPhone Battery Case SE / 5s / 5 plastic and metal.,119.95,0,"5,49E+11",MOP,Mophie
754,MOP0046,Mophie Powerstation 2500mAh External Battery mini USB Black,USB External Battery 2500 mAh with ultrafast charge.,59.95,0,1515,MOP,Mophie
755,MOP0047,Mophie Powerstation 2500mAh External Battery mini USB White,USB External Battery 2500 mAh with ultrafast charge.,59.95,0,1515,MOP,Mophie
807,MOP0053,Mophie 1350mAh External Battery Power Reserve Black Lightning,Lightning external battery connector and 1350 mAh capacity.,49.95,0,1515,MOP,Mophie
808,MOP0055,Mophie 1350mAh External Battery Power Reserve Red Lightning,Lightning external battery connector and 1350 mAh capacity.,49.95,0,1515,MOP,Mophie
825,MOP0056,Mophie Space Pack Battery Case (1700mAh) and Storage 16GB iPhone SE / 5s / 5 Black,Housing with battery and 16GB external storage extras for iPhone SE / 5s / 5,149.99,0,"5,49E+11",MOP,Mophie
1790,MOP0060,Mophie Juice Pack Air Case Battery (2750 mAh) iPhone 6 / 6S Black,Case 2750 mAh battery and LED indicator for iPhone 6 / 6S.,109.99,0,"5,49E+11",MOP,Mophie
1797,MOP0061,Mophie Juice Pack Air Case Battery (2750 mAh) iPhone 6 / 6S White,Case 2750 mAh battery and LED indicator for iPhone 6 / 6S.,109.99,0,"5,49E+11",MOP,Mophie
1801,MOP0062,Mophie Juice Pack Air Case Battery (2750 mAh) iPhone 6 / 6S Dorado,Case 2750 mAh battery and LED indicator for iPhone 6 / 6S.,109.99,0,"5,49E+11",MOP,Mophie
1802,MOP0063,Mophie Juice Pack Plus Battery Case (3300 mAh) iPhone 6 / 6S Black,Case 3300 mAh battery and LED indicator for iPhone 6 / 6S.,129.99,0,"5,49E+11",MOP,Mophie
1803,MOP0064,Mophie Juice Pack Plus Battery Case (3300 mAh) iPhone 6 / 6S White,Case 3300 mAh battery and LED indicator for iPhone 6 / 6S.,129.99,0,"5,49E+11",MOP,Mophie
1804,MOP0065,Mophie Juice Pack Plus Battery Case (3300 mAh) iPhone 6 / 6S Dorado,Case 3300 mAh battery and LED indicator for iPhone 6 / 6S.,129.99,0,"5,49E+11",MOP,Mophie
1805,MOP0066,Mophie Juice Pack Battery Case (2600 mAh) iPhone 6 / 6S Plus Black,Case 2600 mAh battery and LED indicator for iPhone 6 / 6S Plus.,109.99,0,"5,49E+11",MOP,Mophie
1806,MOP0067,Mophie Juice Pack Battery Case (2600 mAh) iPhone 6 / 6S Plus White,Case 2600 mAh battery and LED indicator for iPhone 6 / 6S Plus.,109.99,0,"5,49E+11",MOP,Mophie
1869,MOP0069,Charging Dock Mophie iPhone 5 / 5C / 5S / 6,Lightning dock connector to USB for iPhone 5 / 5S / 5C / 6.,79.99,0,1515,MOP,Mophie
2876,MOP0070,Mophie Juice Pack Pro Waterproof Case + Battery 2750 mAh iPhone 6 / 6S Black,waterproof case with 2750 mAh Battery for iPhone 6 / 6S.,139.95,0,"5,49E+11",MOP,Mophie
2899,MOP0071,Mophie Charging Dock Apple Watch Silver,Charging Stand for Apple Watch.,69.95,0,24215399,MOP,Mophie
3555,MOP0073,Mophie Juice Pack Air Case Battery (2750 mAh) iPhone 6 / 6S Red,Case 2750 mAh battery and LED indicator for iPhone 6 / 6S.,109.99,0,"5,49E+11",MOP,Mophie
4175,MOP0076,Mophie Powerstation 4000mAh USB External Battery 2X Silver,ultra thin aluminum battery 4000mAh 1 USB port for iPad iPhone and iPod,64.95,0,1515,MOP,Mophie
4179,MOP0077,Mophie Space Pack Battery Case (1700mAh) and Storage 32GB iPhone SE / 5s / 5 Gold,Case battery and 32GB for iPhone SE / 5s / 5,179.00,0,"5,49E+11",MOP,Mophie
4182,MOP0078,Mophie Juice Pack Air Case Battery (2750 mAh) iPhone 6 / 6S Lila,Case 2750 mAh battery and LED indicator for iPhone 6 / 6S,109.99,0,11865403,MOP,Mophie
4185,MOP0079,Mophie Juice Pack Air (1700mAh) battery cover iPhone SE / 5s / 5 Red,Plastic and metal case with battery for iPhone SE / 5s / 5,99.95,0,"5,49E+11",MOP,Mophie
4186,MOP0075,Mophie Power Reserve micro USB External Battery 1350mAh Black,small compact external battery and portable device with USB port and microUSB,44.00,1,1515,MOP,Mophie
4271,MOP0021,Mophie Juice Pack Powerstation External Battery iPhone iPad and iPod Black,high-performance external battery iPhone iPad and iPod,59.99,0,1515,MOP,Mophie
4273,MOP0054,Mophie Power Reserve White Lightning externa1350 mAh battery,Lightning external battery connector and 1350 mAh capacity.,49.95,0,1515,MOP,Mophie
4598,MOP0080,Mophie Power Reserve 1X Battery 2600 mAh Black,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1515,MOP,Mophie
4599,MOP0081,Mophie Power Reserve White 2600 mAh battery 1X,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1515,MOP,Mophie
4600,MOP0082,Mophie Power Reserve 2600 mAh battery 1X Blue,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1515,MOP,Mophie
4601,MOP0083,Mophie Power Reserve Rosa 1X Battery 2600 mAh,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1515,MOP,Mophie
4602,MOP0084,Mophie Power Reserve 2600 mAh battery 1X White / Pink Gold,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1515,MOP,Mophie
4603,MOP0085,Mophie Powerstation 6000mAh battery 3X Aluminum,ultra thin aluminum battery 6000mAh 2 USB ports for iPhone iPad and iPod,84.95,0,1515,MOP,Mophie
4604,MOP0086,Mophie Powerstation 5X battery 10000mAh Aluminum,aluminum battery ultra thin 10.000mAh 2 USB ports high speed for iPad iPhone and iPod,139.95,0,1515,MOP,Mophie
4605,MOP0087,Mophie Powerstation 8X Aluminum 15000mAh Battery,aluminum battery ultra thin 15.000mAh 2 USB ports high speed for iPad iPhone and iPod,159.95,0,1515,MOP,Mophie
4606,MOP0072,Mophie Juice Pack Reserve Battery Case 1840 mAh iPhone 6 / 6S Black,Case 1840 mAh battery and LED indicator for iPhone 6 / 6S.,69.95,0,"5,49E+11",MOP,Mophie
4607,MOP0088,Mophie Juice Pack Reserve Battery Case 1840 mAh iPhone 6 / 6S Rose Gold,Case 1840 mAh battery and LED indicator for iPhone 6 / 6S,69.95,0,"5,49E+11",MOP,Mophie
4809,MOP0089,Mophie Juice Pack 1560mAh + Wireless Charging Dock iPhone 6 / 6S Black,1560mAh battery cover most wireless charging base for iPhone 6s / 6,109.95,0,"5,49E+11",MOP,Mophie
4810,MOP0090,Mophie Juice Pack 2.420mAh + Wireless Charging Dock iPhone 6 / 6S Plus Black,Wireless battery cover with 2.420mAh more base load for iPhone 6s / 6 Plus,129.95,0,"5,49E+11",MOP,Mophie
5440,MOP0074,Mophie Powerstation External Battery Cable Plus,Aluminum laptop battery cable included 7000 mAh for iPad and iPhone,99.00,0,1515,MOP,Mophie
5712,MOP0058-A,(Open) Mophie Juice Pack Plus Battery Case (3300 mAh) iPhone 6 / 6S White,Case 3300 mAh battery and LED indicator for iPhone 6 / 6S.,129.99,0,1298,MOP,Mophie
5753,MOP0091,Mophie Battery 1400mAh Power Capsule micro USB Adapter,More battery carrying case for wireless headsets and sports gadgets,39.95,1,1515,MOP,Mophie
5773,MOP0095,Mophie Hold Force Base Case Wrap Case iPhone 7 Plus,Case Ultra Thin magnetic plate on the back to attach accessories iPhone 7 Plus,39.95,1,11865403,MOP,Mophie
5774,MOP0094,Hold Force Base Case Mophie iPhone Case 7 Plus Gradient,Case Ultra Thin magnetic plate on the back to attach accessories Force Hold iPhone 7 Plus,39.95,1,11865403,MOP,Mophie
5775,MOP0093,Hold Force Base Case Mophie iPhone Case 7 Plus Black,Case Ultra Thin magnetic plate on the back to attach accessories iPhone 7 Plus,39.95,1,11865403,MOP,Mophie
5782,MOP0096,Hold Force Base Case Mophie iPhone Case 7 Black,Case Ultra Thin magnetic plate on the back to attach accessories iPhone 7,39.95,1,11865403,MOP,Mophie
5783,MOP0097,Hold Force Base Case Mophie iPhone Case 7 Gradient,Case Ultra Thin magnetic plate on the back to attach accessories 7 Hold Force for iPhone,39.95,1,11865403,MOP,Mophie
5784,MOP0098,Hold Force Base Case Mophie iPhone Case 7 Black / Transparent,Case Ultra Thin magnetic plate on the back to attach accessories 7 Hold Force for iPhone,39.95,0,11865403,MOP,Mophie
5785,MOP0099,Hold Force Base Case Mophie iPhone Case 7 Wrap,Case Ultra Thin magnetic plate on the back to attach accessories 7 Hold Force for iPhone,39.95,0,11865403,MOP,Mophie
5864,MOP0100,Mophie Powerstation 6000mAh Battery Plus Space Gray,externado 6000 mAh battery with micro USB for iPhone iPad and iPod,89.95,0,1515,MOP,Mophie
5866,MOP0030-A,(Open) Mophie Juice Pack Air (1700mAh) battery cover iPhone SE / 5s / 5 gold,IPhone Battery Case SE / 5s / 5 plastic and metal.,99.95,0,1298,MOP,Mophie
6221,MOP0101,Mophie Juice Pack Reserve Battery Case 1840 mAh iPhone 6 / 6s Blue,Case 1840 mAh battery and LED indicator for iPhone 6 / 6S,69.95,0,11865403,MOP,Mophie
6458,MOP0074-A,Open - Mophie Power Reserve 1X Battery 2600 mAh Black,Laptop Battery 2600mAh (18A) with LED and micro / USB connection for iPhone,39.95,0,1298,MOP,Mophie
9279,MOP0103,Mophie Wireless Charging Base for iPhone,Qi charging dock with iPhone technology for wireless charging,64.99,1,13615399,MOP,Mophie
9588,MOP0110,Mophie Juice Pack Air Battery Case for iPhone 2.420mAh 8 Plus / 7 Plus Blue,Mophie Battery Case for iPhone 2.420mAh 8 Plus or 7-Plus,99.95,1,11865403,MOP,Mophie
9589,MOP0111,Mophie Juice Pack Air Battery Case for iPhone 2.420mAh 8 Plus / 7 Red Plus,Mophie Battery Case for iPhone 2.420mAh 8 Plus or 7-Plus,99.95,1,11865403,MOP,Mophie
9590,MOP0112,Mophie Juice Pack Air Battery Case for iPhone 2.420mAh 8 Plus / 7 Black Plus,Mophie Battery Case for iPhone 2.420mAh 8 Plus or 7-Plus,99.95,0,11865403,MOP,Mophie
9783,MOP0107,Mophie Powerstation 4000mAh Battery Plus Mini Universal Space Gray,external battery capacity 4000mAh output voltage 5V,69.95,0,1515,MOP,Mophie
9784,MOP0108,Mophie Powerstation Mini Universal 4000mAh Battery Plus Gold,external battery capacity 4000mAh output voltage 5V,69.95,0,1515,MOP,Mophie
9785,MOP0109,Mophie Powerstation Mini Universal 4000mAh Battery Plus Rose Gold,external battery capacity 4000mAh output voltage 5V,69.95,0,1515,MOP,Mophie
9807,MOP0113,Mophie Juice Pack Air Battery Case iPhone 8/7 Blue,Mophie Juice Pack Air Case with battery for Apple iPhone 8/7 2.525mAh,99.95,1,11865403,MOP,Mophie
9808,MOP0114,Mophie Juice Pack Air Battery Case iPhone 8/7 Red,Mophie Juice Pack Air Case with battery for Apple iPhone 8/7 2.525mAh,99.95,1,11865403,MOP,Mophie
9872,MOP0105,Mophie Powerstation 6000mAh battery Universal Plus Rose Gold,external battery capacity 6000mAh output voltage 5V,89.95,0,1515,MOP,Mophie
9873,MOP0106,Mophie Powerstation 6000mAh battery Universal Plus Gold,external battery capacity 6000mAh output voltage 5V,89.95,0,1515,MOP,Mophie

In [23]:
pbm.loc[pbm["short"] == "JYB", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
8105,JYB0007,X3 Jaybird Wireless Bluetooth Headset Black,In-ear headphones waterproof and wireless 8 hours of autonomous iPhone iPad iPod powder and Apple Watch,129.00,0,5384,JYB,Jaybird
8106,JYB0008,Jaybird Freedom Bluetooth Headphones Red,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384,JYB,Jaybird
8107,JYB0009,Jaybird Freedom Bluetooth Headphones White,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384,JYB,Jaybird
8108,JYB0010,Jaybird Freedom Bluetooth Headphones Black,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384,JYB,Jaybird

In [24]:
pbm.loc[pbm["short"] == "KEN", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
40,KEN0028,Kensington ClickSafe lock Mac and PC,Mac and PC padlock with keys.,54.99,0,1325,KEN,Kensington
85,KEN0045,Kensington Essentials Stand iPad Stand black,Universal support for iPad tablets.,29.99,0,1216,KEN,Kensington
86,KEN0046,Kensington Essentials Stand iPad Stand white,Universal support for iPad tablets.,19.99,0,1216,KEN,Kensington
194,KEN0059,Kensington Soft Case cover iPhone 5 / 5S black,Soft Case iPhone 5 / 5S.,14.99,0,11865403,KEN,Kensington
195,KEN0062,Kensington Thin Back Case iPhone 5 / 5S Gray,Back Case iPhone 5 / 5S.,19.99,0,11865403,KEN,Kensington
196,KEN0063,Kensington Thin Back Case iPhone 5 / 5S Pink,Back Case iPhone 5 / 5S.,19.99,0,11865403,KEN,Kensington
318,KEN0064,"Safestand Kensington security lock iMac 27 """,key lock station for iMac 27 inches.,99.99,0,1325,KEN,Kensington
338,KEN0078,Kensington Easy Riser Notebook PC and Mac,Support for Mac portable and adjustable PC.,24.99,0,8696,KEN,Kensington
339,KEN0079,Kensington Expert Presenter Green Laser Pointer,laser pointer 10X bright green.,76.99,0,1229,KEN,Kensington
341,KEN0080,Kensington Presenter Expert green laser pointer with 4GB,laser pointer green + USB 4GB 10 times brighter,89.99,0,1229,KEN,Kensington
342,KEN0081,Kensington Expert Presenter Red Laser Pointer,Red laser pointer for presentations color.,49.99,0,1229,KEN,Kensington
346,KEN0093,ClickSave Kensington Laptop Cable Lock,Security cable with combination laptop Mac and PC.,49.99,0,1325,KEN,Kensington
347,KEN0094,"Kensington Cable, retractable Mac and PC",retractable cable Mac and PC combination.,29.99,1,1325,KEN,Kensington
366,KEN0096,Kensington Evap Water Rescue Pouch bag wet salvation,Salvation bag for iPhone and iPod exposed to moisture.,19.99,0,11905404,KEN,Kensington
392,KEN0105,Kensington MicroSaver Keyed security lock MacBook UltraBook,cable lock with safety lock for MacBook.,69.99,0,1325,KEN,Kensington
496,KEN0109,"Backpack Trek Triple Kensington MacBook 13 ""Black",Backpack for MacBook Pro / Air 13-inch,60.49,0,1392,KEN,Kensington
497,KEN0110,"Bandolier Trek Triple Kensington MacBook 13 """,Triple Trek bandolier for your MacBook Pro / Air 13 inches.,43.99,0,1392,KEN,Kensington
498,KEN0111,"Triple Kensington Trek briefcase MacBook 13 ""Black",briefcase vertical opening for MacBook / Air 13 inches.,54.99,0,1392,KEN,Kensington
577,KEN0129,Portofolio Kensington Soft Case iPad Mini / Retina Green,Flexible Book cover type for new iPad Mini Retina.,28.99,0,12635403,KEN,Kensington
731,KEN0166,PowerBolt Kensington 3.4 Dual Charger with Lightning Cable Car,Car Charger fast charging with double connection: USB (1A) and Lightning cable (24A) for iPhone and iPad,43.99,0,13615399,KEN,Kensington
780,KEN0172,Kensington GummyGrip Kids Children Pointer iPad Gray,Children pointer with thick tip for iPad iPhone and iPod Touch.,12.99,0,1229,KEN,Kensington
782,KEN0171,Kensington Absolute Power International Power Adapter,International Adapter with 2 USB ports entry USA / Japan Australia / UK and European China.,34.99,0,14365395,KEN,Kensington
799,KEN0174,Kensington SafeGrip iPad Air Rugged Case with Stand NII ± or Carbon,Shockproof housing for children with handle for iPad.,43.99,0,12635403,KEN,Kensington
804,KEN0175,Kensington SafeGrip iPad Air Rugged Case with Stand NII ± or Blue,Shockproof housing with handle for iPad.,43.99,0,12635403,KEN,Kensington
854,KEN0179,Kensington BlackBelt 2nd Degree Case iPad Mini / Retina Lila,Shock resistant housing military rubber for iPad Mini / Retina.,39.99,0,12635403,KEN,Kensington
1230,KEN0194,Kensington 7-port USB 3.0 pockethub,Charger and USB 3.0 HUB with 7 ports.,59.99,0,13005399,KEN,Kensington
1354,KEN0196,Kensington Folio Case Cover Customize Me iPad Air 2 Red,Lockable customizable universal type book for iPad Air 2.,39.99,0,12635403,KEN,Kensington
1392,KEN0206,UA3000E Kensington USB 3.0 to Ethernet Adapter Gigabyte USB 3-Port Hub + 3.0,Adapter USB 3.0 to Ethernet Hub Gigabyte and 3 USB 3.0 ports for Mac and PC.,56.09,0,12585395,KEN,Kensington
1393,KEN0209,UH4000 Kensington 4-Port USB 3.0 Hub,Hub 4 USB 3.0 ports for Mac and PC.,27.49,0,12995397,KEN,Kensington
1410,KEN0208,Kensington UH4000C Hub 4 port power supply,Mac and PC Hub 4 USB 3.0 ports.,44.99,0,12995397,KEN,Kensington
1420,KEN0195,Kensington Folio Case Cover Customize Me iPad Air 2 Black,customizable cover with book closure type for iPad Air 2,39.99,0,12635403,KEN,Kensington
1436,KEN0200,Kensington KeyFolio Plus X2 Thin Case with backlit keyboard iPad Air 2 Black,Cover with Spanish backlit keyboard for iPad Air 2,109.99,0,12575403,KEN,Kensington
1458,KEN0211,Kensington Power Bank 10400 mAh External Battery,10400mAh external battery small and light for iPhone iPad and iPod.,59.99,0,1515,KEN,Kensington
1475,KEN0204,"Bandolier LM340 Kensington 14.4 ""Gray",Padded shoulder strap with compartments and Macbook cases up to 144 inches.,49.99,0,1392,KEN,Kensington
1527,KEN0201,Kensington KeyFolio X3 Thin Keyboard and Case for iPad Air 2 Battery Black,Spanish keyboard holster and battery for iPad Air 2,109.99,0,12635403,KEN,Kensington
1586,KEN0207,Kensington UA0000E Gigabyte Ethernet Adapter USB 3.0,Gigabyte Ethernet adapter to USB 3.0.,29.99,0,12585395,KEN,Kensington
1823,KEN0212,Kensington Power Bank External Battery 5200mAh Silver,5200mAh external battery small and light (152g) for iPhone iPad and iPod.,32.99,0,1515,KEN,Kensington
2072,KEN0210,PresentAir Kensington Presenter Pro Bluetooth 4.0 LE,Bluetooth laser pointer.,59.99,0,12085400,KEN,Kensington
2267,KEN0218,Slot Adapter Kit security Kensington,Safety kit with adapter slot MacBook Air.,16.49,0,12355400,KEN,Kensington
2289,KEN0203-A,(Open) UH4000 Kensington 4-Port USB 3.0 Hub,Hub 4 USB 3.0 ports for Mac and PC.,27.49,0,1298,KEN,Kensington
2388,KEN0220,Kensingnton Minisaver security Cable for Mac and PC,Cable ultralight Mac and PC security.,69.99,0,1325,KEN,Kensington
2390,KEN0223,Kensington BlackBelt 1st Degree Rugged Case for iPad Air 2 Black,Black Case for iPad Air 2.,29.99,0,12635403,KEN,Kensington
2391,KEN0224,Kensington BlackBelt 2nd Degree Rugged Case for iPad Air 2 Black,Shock resistant housing rubber IPAD Air 2.,44.99,0,12635403,KEN,Kensington
2392,KEN0225,Kensington SafeGrip Case for iPad mini resistant Verde,Hard Case for iPad Mini with handle.,39.99,0,12635403,KEN,Kensington
2394,KEN0227,Kensington BlackBelt 1st Degree Rugged Case for iPad Mini Black,Light and protective cover for iPad Mini.,24.99,0,12635403,KEN,Kensington
2396,KEN0226,Kensington BlackBelt 2nd Degree Rugged Case for iPad Mini Black,Shock resistant housing military rubber iPad Mini.,34.99,0,12635403,KEN,Kensington
3006,KEN0230,VM1000 Kensington Mini DisplayPort to VGA 2K,Video Adapter Mini Display to VGA.,29.99,0,12585395,KEN,Kensington
3008,KEN0229,VM2000 Kensington Mini DisplayPort to HDMI Adapter 2K,Video Adapter Mini Display to HDMI.,29.99,0,12585395,KEN,Kensington
3163,KEN0232,VM4000 Kensington Mini Display Port Adapter to HDMI 4K,4K resolution video adapter Mini Display to HDMI.,36.99,0,12585395,KEN,Kensington
3630,KEN0235,Kensington SecureBack Air Rugged Case 1/2 Black,Ultra-resistant sleeve anchor with click and lock iPad Air 1/2,60.99,0,12635403,KEN,Kensington
3653,KEN0234,SecureBack Kensington Case iPad Air / 2 Black,Cover with click and lock anchor for iPad Air 1/2.,59.99,0,12635403,KEN,Kensington
3764,KEN0236,Kensington MP230L black mouse accuracy,Precision Wireless Mouse for Mac and PC.,59.99,0,1387,KEN,Kensington
3832,KEN0237,Kensington MicroSaver Security Cable 18m,Security Cable lock for Mac and PC laptops.,49.49,0,1325,KEN,Kensington
4547,KEN0240,Kensington PowerBolt 5.2A Dual USB Car Charger,26W Car Charger Dual USB for iPhone and iPad,29.99,0,13615399,KEN,Kensington
4548,KEN0241,Kensington PowerBolt fast car charger 2.4A,Car Charger with USB 2.0 port for fast charging for iPad iPhone and iPod,19.99,0,13615399,KEN,Kensington
4549,KEN0242,SD3500v Kensington Docking USB 3.0 / DVI / HDMI / Ethernet,Dock with multiple USB connections 3.0 DVI / HDMI / DVI and Ethernet adapters VGA / HDMI for Mac and PC,194.99,0,12995397,KEN,Kensington
4583,KEN0243,Dock Kensington USB-C to USB 3.1 / USB-C / Ethernet / HDMI,USB-Hub USB 3.1 ports C / USB-C / Ethernet / HDMI (compatible with Thunderbolt 3) for Mac and PC,310.99,0,12585395,KEN,Kensington
4586,KEN0238,Kensington Lift Off MacBook Support,Support and height-adjustable base with ventilation slot MacBook,29.99,0,8696,KEN,Kensington
4596,KEN0239,Kensington Support Macbook with fan,Stand with two fans and USB connection for MacBook,39.99,0,8696,KEN,Kensington
4739,KEN0228,Kensington Docking Station USB 3.0 to VGA / HDMI / DVI,Dock with 6 USB ports and dual video connector for Mac and PC,164.99,0,12995397,KEN,Kensington
4772,KEN0244,Dock Kensington SD4500 USB USB 3.1-C / Ethernet / HDMI,Dock USB-C USB 3.1 Ethernet HDMI (compatible with Thunderbolt 3) for Mac,279.99,0,12585395,KEN,Kensington
5298,KEN0245,Kensington USB Dock SD1500-C to USB 3.0 / HDMI / VGA / Ethernet Notebook,Laptop Dock with 4 ports and 4K video output cable included USB-C for Mac and PC,105.99,0,12585395,KEN,Kensington
6364,KEN0237-A,Open - Kensington USB-C USB 3.1 ports Dock / USB-C / Ethernet / HDMI / Thunderbolt 3,Dock USB-C USB 3.1 / USB-C / Ethernet / HDMI / 3-port Thunderbolt Mac and PC,310.99,0,12585395,KEN,Kensington
6466,KEN0247,CV2000V Kensington USB-C to VGA Full HD Black,USB-C adapter with VGA resolution FHD for Mac and PC,36.29,0,12585395,KEN,Kensington
6470,KEN0248,CV4000H Kensington USB adapter to HDMI 4K-C Black,USB-C adapter supports HDMI 4K resolution for Mac and PC,49.99,0,12585395,KEN,Kensington
7771,KEN0249,Kensington Security Locking Station 2.0 Adapter MacBook,Adapter anchoring safety key and compact design for MacBook model 11 inches to 15 inches,120.01,0,12355400,KEN,Kensington
8382,KEN0239-A,Open - Kensington USB Dock SD1500-C to USB 3.0 / HDMI / VGA / Ethernet Notebook,Refurbished Laptop Dock with 4 ports and 4K video output cable included USB-C for Mac and PC,105.99,0,1298,KEN,Kensington

In [25]:
brands_df.loc[brands_df["short"] == "KEN", "long"] = "Kensington"

In [26]:
brands_df.loc[brands_df["short"] == "KEN", :]

   short        long
70   KEN  Kensington

In [27]:
pbm.loc[pbm["short"] == "CAD", :].shape[0]

0

In [28]:
pbm.loc[pbm["short"] == "ENV", :].shape[0]

0

In [29]:
pbm.loc[pbm["short"] == "LIB", :].shape[0]

0

In [30]:
pbm.loc[pbm["short"] == "STA", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
793,STA0016,Startech Mini DisplayPort to DisplayPort Cable 18m,Adapdator Cable Mini Display Port Male to Display Port.,12.99,0,1325,STA,Startech
923,STA0013,Startech USB 2.0 cable type A male B 5m,USB 2.0 cable type A male B 5m.,6.99,1,1325,STA,Startech
1583,STA0009,Startech HDMI M / M Black 2m,Cable HDMI M / M black 2 meters.,12.99,1,1325,STA,Startech
1592,STA0017,Startech HDMI M / M Ultra HD 4K Black 3m,Cable HDMI M / M 3m Ultra HD 4k black 3D Ready and Ethernet.,14.99,1,1325,STA,Startech
1595,STA0018,Startech HDMI M / M Ultra HD 4K Black 5m,Cable HDMI M / M 5m Ultra HD 4K 3D Ready and Ethernet.,19.99,1,1325,STA,Startech
1814,STA0020,Startech Ethernet cable 15 meters Gray Unit Class 6,Ethernet cable 15 meters Unit Class 6 Mac and PC.,16.99,1,1325,STA,Startech
1821,STA0011,Startech USB Cable black 18m extension,18 meters extension USB cable.,4.79,0,1325,STA,Startech
1936,STA0019,Startech Adapter with Micro Mini-Jack 35mm 2 connectors,Adapter headset jack Mini-4-pin mini-jack 2 3 pin.,9.99,0,1325,STA,Startech
2104,STA0008,Startech DVI-D dual link M / M 18m,Cable DVI-D 18 double bond meters.,11.99,0,1325,STA,Startech
2166,STA0030,Startech Adapter Cable Lightning to Micro USB-B Female Black,Cable Lightning to Micro USB adapter for charging and syncing for iPhone iPad and iPod Touch.,22.99,0,1325,STA,Startech
2199,STA0021,Startech HDMI M / M black 1mt,HDMI Cable 1 meter with 2 male ports for Mac.,9.99,1,1325,STA,Startech
2316,STA0022,Startech Video Converter Cable Mini DisplayPort to VGA,Cable Mini DisplayPort to VGA.,41.99,1,1325,STA,Startech
2323,STA0023,Startech Adapter Kit Mini DisplayPort / VGA / HDMI / USB 3.0 / Gigabit Ethernet,Mini DisplayPort adapter kit / HDMI / VGA / USB 3.0 / Ethernet.,86.99,0,1325,STA,Startech
2324,STA0024,Startech Adapter Kit Ethernet / USB 3.0 / VGA / Mini DisplayPort,Two adapter cables Mini DisplayPort to VGA and USB 3.0 to Ethernet.,81.99,0,1325,STA,Startech
2325,STA0025,Startech 21A Lightning Car Charger with USB 2.0,Dual car charger Lightning and USB 2.0 for iPhone and iPad.,44.99,0,13615399,STA,Startech
2326,STA0026,Startech Adapter Lightning to Micro USB-B Female White,Lightning to Micro USB Adapter for iPhone-B generation iPad and iPod Touch 6A.,16.99,0,14365395,STA,Startech
2327,STA0027,Startech Lightning to USB Cable 30cm Black,Lightning 30cm USB cable to charge and sync iPhone iPad and iPod.,19.99,0,1325,STA,Startech
2328,STA0028,Startech Adapter Cable Lightning to Micro USB-B Female White,Cable Lightning to Micro USB adapter for charging and syncing for iPhone iPad and iPod Touch.,22.99,0,1325,STA,Startech
2329,STA0029,Startech Lightning to USB Cable 3m White,Lightning 3 m Cable for iPhone iPad and iPod Touch.,30.99,0,1325,STA,Startech
2330,STA0031,Startech Lightning to USB Cable 1m,Lightning USB cable 1m for charging and syncing iPhone iPad and iPod.,15.99,0,1325,STA,Startech
3800,STA0010-A,Open - Startech Cable Mini Display Port to Display Port 18m,Adapdator Cable Mini Display Port Male to Display Port,12.99,0,1298,STA,Startech
5780,STA0032,Startech Gigabit Ethernet Cable Cat. 6 2m Gray,Ethernet Cable 2 meters Mac and PC Unit Class 6,4.99,1,1325,STA,Startech
5781,STA0033,StarTech Gigabit Ethernet Cable Cat. 6 5m Gray,Ethernet Cable 5 meter Mac and PC Unit Class 6,7.99,1,1325,STA,Startech
6059,STA0034,Startech Adapter Black Thunderbolt Thunderbolt 3,Thunderbolt adapter 3 USB- C Thunderbolt first generation Thunderbolt 2,135.99,0,12585395,STA,Startech
6060,STA0035,USB-C Startech VGA Adapter Black,Adapter with reversible USB connection VGA-C (compatible with Thunderbolt 3) Mac and PC,53.99,1,12585395,STA,Startech
6061,STA0036,Startech USB Adapter VGA-C Blanco,Adapter with reversible USB connection VGA-C (compatible with Thunderbolt 3) Mac and PC,53.99,1,12585395,STA,Startech
6062,STA0031-A,Open - Startech USB-C HDMI Adapter Black,Adapter with USB-C reversible HDMI connection supports Mac and PC conThunderbolt 3,39.99,0,1298,STA,Startech
6063,STA0038,Startech USB adapter to HDMI-C White,Adapter with reversible USB-C connection HDMI (compatible with Thunderbolt 3) Mac and PC,39.99,1,12585395,STA,Startech
6064,STA0042,Startech USB Adapter DVI-C White,Adapter with USB-C reversible Digital DVI connection (compatible with Thunderbolt 3) Mac and PC,49.99,1,12585395,STA,Startech
6065,STA0039,Hub Startech USB to VGA DVI-C Mini DisplayPort HDMI and 4K Aluminum,Hub Thunderbolt connection 3 / USB-C VGA DVI to HDMI and Mini DisplayPort and integrated magnetic cable manager for Mac and PC,128.99,1,12585395,STA,Startech
6069,STA0040,Startech USB Hub Charger-C to HDMI 4K 2 USB 3.0 ports and Ethernet Gigabite,Hub Thunderbolt connection 3 / USB to HDMI 4K-C Gigabit Ethernet port and two USB 3.0 ports for Mac and PC,146.99,1,12585395,STA,Startech
6070,STA0041,Startech USB Hub-C or VGA to HDMI 4K USB 3.0 and Gigabit Ethernet,Hub with USB-C connection VGA port or HDMI 4K Gigabit Ethernet port and USB 3.0 for Mac and PC,123.99,1,12585395,STA,Startech
6082,STA0048,Startech USB-C to USB-C Cable 1m Black (compatible with Thunderbolt 3-port),USB cable connection USB-C-C and reversible design for Mac and PC,14.99,0,1325,STA,Startech
6083,STA0060,Startech USB-C Gigabit Ethernet Adapter White,USB-C adapter Gigabit Ethernet high-performance Mac and PC,52.99,1,12585395,STA,Startech
6084,STA0050,Startech USB-C Gigabit Ethernet Adapter Silver,C adapter with USB-Gigabit Ethernet connection with compact aluminum design for Mac and PC,63.59,1,12585395,STA,Startech
6085,STA0047,Startech USB Hub-C and 3-C USB USB-A Black,Hub with USB-C connection 3 USB-A ports and 1 USB-C port (compatible with Thunderbolt 3) for Mac and PC,52.99,1,12585395,STA,Startech
6086,STA0054,Startech USB Hub 3-C USB 3.0 and Gigabit Ethernet Power Adapter,Hub with USB-C connection 3 USB 3.0 ports and an additional port Gigabit Ethernet with power adapter for Mac and PC,93.99,1,12585395,STA,Startech
6087,STA0051,Startech USB-C 4K HDMI 60Hz Black,USB-C adapter with HDMI connection (compatible with Thunderbolt 3) for Mac and PC,47.99,1,12585395,STA,Startech
6089,STA0049,Startech USB-C Adapter USB 3.1 Gigabit Ethernet + Extra Black,USB-C adapter cable (compatible with Thunderbolt 3) and two connections: Ethernet and USB 3.1 for new MacBook,70.99,0,12585395,STA,Startech
6090,STA0061,Startech USB-C Gigabit Ethernet Adapter 2 + USB 3.0 Extra Black,USB-C adapter cable (compatible with Thunderbolt 3) Two Gigabit Ethernet ports and 1 USB 3.0 port for new MacBook,109.99,0,12585395,STA,Startech
6092,STA0053,Startech Reader / Writer SD Card 4.0 UHS II 2 slots for USB-C,SD reader and writer SDHC or SDXC cards and USB 3.0 and USB -C connection for Mac and PC,68.99,0,12585395,STA,Startech
6093,STA0062,Startech Mini DisplayPort to DisplayPort Cable 18m 4k Black,Cable adapter Mini Displayport to Displayport compatible with 4K content for Mac and PC,11.99,0,1325,STA,Startech
6094,STA0063,StarTech Cable FireWire 800 9-6 pins 18m Black,FireWire Cable Firewire 800 connection with 9-pin to 6-pin Firewire for Mac and PC,14.99,0,1325,STA,Startech
6102,STA0043,Startech charging cable Thunderbolt 3 05m Black (compatible USB-C),Cable length 05 m with connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,33.99,1,12585395,STA,Startech
6103,STA0044,Startech charging cable 1m Thunderbolt 3 20Gb / s (compatible USB-C) Black,Cable length 3 to 1 meter Thunderbolt Thunderbolt connection 3 for Mac and PC,39.99,1,1325,STA,Startech
6104,STA0045,Startech charging cable 2m Thunderbolt 3 20Gb / s (compatible USB-C),Cable length 2 meters connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,49.99,1,1325,STA,Startech
6110,STA0046,Startech USB-C Mini Adapter USB-A Black,Adapter with USB-C connection to USB-A compatible with Thunderbolt 3 for Mac and PC,20.99,1,12585395,STA,Startech
6111,STA0052,Startech USB-C 4K HDMI 60Hz White,C USB-HDMI adapter compatible with Thunderbolt 3 Connection for Mac and PC,47.99,1,12585395,STA,Startech
6112,STA0058,Startech USB-C to DVI Cable 1m Black,With reversible USB-adapter C Digital DVI connection for Mac and PC,53.99,0,12585395,STA,Startech
6113,STA0059,Startech USB-C Cable to VGA 1m Black,1m adapter cable with USB-C reversible VGA connection for Mac and PC,62.99,0,12585395,STA,Startech
6119,STA0055,Startech USB-C Adapter USB-A Black,Cable adapter with USB-C to USB 3.0 connection compatible with Thunderbolt 3 for Mac and PC,22.99,1,12585395,STA,Startech
6121,STA0056,Startech USB-C Cable DisplayPort 18m 60Hz 4K Black,18m adapter cable with USB-C connection DisplayPort 4K resolution for Mac and PC,53.99,1,12585395,STA,Startech
6122,STA0057,Startech USB-C Cable to HDMI 4K 30Hz 2m Black,2 m Cable adapter with USB-C connection to HDMI 4K 30Hz and compact design for Mac and PC,58.99,1,12585395,STA,Startech
6244,STA0039-A,Open - Startech Charging Cable Black 2m Thunderbolt 3,Cable length 2 meters connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,49.99,0,1298,STA,Startech
6387,STA0032-A,Open - Startech Thunderbolt Adapter 3 / USB to HDMI-C White,Thunderbolt adapter plug 3 / USB-C HDMI reversibly with light weight design and easy portability,39.99,0,1298,STA,Startech
6429,STA0043-A,Open - Startech Thunderbolt Adapter 3 / USB-C to USB 3.1 Gigabit Ethernet + Extra Black,Thunderbolt cable adapter 3 / USB-C and two connections: Ethernet and USB 3.1 for new MacBook,70.99,0,1298,STA,Startech
6434,STA0047-A,Open - Startech Reader / Writer SD Card 4.0 UHS II 2 slots for USB-C,SD reader and writer SDHC or SDXC cards and USB 3.0 and USB -C connection for Mac and PC,68.99,0,1298,STA,Startech
6645,STA0044-A,Open - USB-C Startech Gigabit Ethernet Adapter Silver,USB-C Gigabit Ethernet connection with compact aluminum design for Mac and PC,63.59,0,1298,STA,Startech
6902,STA0064,StarTech Thunderbolt Docking Station 3 With Dual Outputs 4K video,Hub Thunderbolt 3 to multiport USB USB-C 3.1Ethernet audio output and audio input for Mac and PC,422.28,1,12585395,STA,Startech
7694,STA0041-A,Open - Startech USB Hub USB-C-C and 3 USB-A Black,Hub with USB-C connection 3 USB-A ports and 1 USB-C port (compatible with Thunderbolt 3) for Mac and PC,52.99,0,1298,STA,Startech
7696,STA0020-A,Open - Startech Adapter Lightning to Micro USB-B Female White,Lightning to Micro USB Adapter for iPhone-B generation iPad and iPod Touch 6A.,16.99,0,1298,STA,Startech
8676,STA0037,Startech USB-C HDMI Adapter Black,Adapter with USB-C reversible HDMI connection supports Mac and PC conThunderbolt 3,39.99,0,12585395,STA,Startech
9508,STA0033-A,Open - Hub Startech USB to VGA DVI-C Mini DisplayPort HDMI and 4K Aluminum,Hub Thunderbolt connection refitted with 3 / USB-C VGA DVI to HDMI and Mini DisplayPort and integrated magnetic cable manager for Mac and PC,128.99,0,12585395,STA,Startech
9924,STA0035-A,Open - Startech USB Hub-C or VGA to HDMI 4K USB 3.0 and Gigabit Ethernet,Hub with USB-C connection VGA port or HDMI 4K Gigabit Ethernet port and USB 3.0 for Mac and PC,123.99,0,12585395,STA,Startech

In [31]:
pbm.loc[pbm["short"] == "OTR", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
82,OTR0045,External Slim Case for SuperDrive MacBook / MacBook Pro,External SuperDrive case for MacBook and MacBook Pro.,35.00,1,12995397,OTR,Startech
276,OTR0062,StarTech USB adapter mini Bluetooth 2.1,Mini Bluetooth USB for Mac and PC wireless network.,24.99,0,1334,OTR,Startech
281,OTR0039,Startech Splitter Adapter 2 headphones,headphone jack adapter 2 Mini-3-pin mini-jack to 4 pin.,9.20,1,1230,OTR,Startech
692,OTR0103,Grenade Grip Gopole EmpuÌ ± Adura GoPro camera,EmpuÌ ± Adura for GoPro Hero.,22.99,0,11905404,OTR,Startech
693,OTR0104,Xsories Big U-Shot GoPro Camera Extension 95cm Black,95cm extension rod GoPro Hero cameras.,49.99,0,11905404,OTR,Startech
694,OTR0107,Xsories 50cm extension U-Shot camera GoPro Silver,Extension Arm for GoPro Hero.,49.99,0,11905404,OTR,Startech
928,OTR0075,Startech Ethernet Cable Cat6 10m Black,Ethernet cable 10 meters Unit Class 6 Mac and PC.,11.99,1,1325,OTR,Startech
929,OTR0092,StarTech HDMI Extension Cable 2m Black,StarTech HDMI Extension Cable 2m Black.,11.99,0,1325,OTR,Startech
932,OTR0031,Startech Cable DVI-I Male to DVI-I (29-pin) 18m,Cable DVI-I Male to DVI-I 18m.,14.98,0,1325,OTR,Startech
1414,OTR0120,selfie extendable arm with black Bluetooth button,extensible arm Bluetooth button for selfies.,24.99,0,1216,OTR,Startech
1455,OTR0119,Pinpo extensible arm selfie + self-timer,Extensible arm for selfies and self-timer for iPhone.,14.99,0,11905404,OTR,Startech
2098,OTR0124,Deeper- Smart Fishfinder Sonar fish,Finder portable wireless fish for iPhone iPad and iPod Touch.,259.99,0,11905404,OTR,Startech
3299,OTR0039-A,Open - External Slim Case for SuperDrive MacBook / MacBook Pro,Reconditioned external box SuperDrive for MacBook and MacBook Pro,35.00,0,12995397,OTR,Startech
4557,OTR0130,"Brenthaven Fusion case for MacBook Pro Retina 13 ""Black / Green",briefcase with 10 pockets and zippers compartments MacBook Pro Retina 13 / Air 11 inches / 12 inches MacBook / IPAD Pro 129 inches,99.99,0,1392,OTR,Startech
5708,OTR0025-A,Open - Startech Cable DVI-I Male to DVI-I (29-pin) 18m,Cable DVI-I Male to DVI-I 18m.,14.98,0,1298,OTR,Startech

In [32]:
pbm.loc[pbm["type"] == "12995397", :]#.shape[0]

,sku,name,desc,price,in_stock,type,short,long
17,HGD0007,"Henge Docks Docking Station MacBook Pro 13 """,Dock and support with multiple connections for MacBook Pro 13-inch.,69.99,0,12995397,HGD,Henge Docks
82,OTR0045,External Slim Case for SuperDrive MacBook / MacBook Pro,External SuperDrive case for MacBook and MacBook Pro.,35.00,1,12995397,OTR,Startech
133,DLK0011,D-Link DUB-1340 Hub 4 x SuperSpeed ​​USB 3.0 Mac and PC,Dlink USB Hub Mac and PC 4 port.,64.00,0,12995397,DLK,D-Link
134,DLK0012,D-Link DUB-H7 Hub 7 x Hi-Speed ​​USB Mac and PC,Dlink USB Hub Mac and PC 7 ports.,33.99,0,12995397,DLK,D-Link
148,NTE0011,NewerTech miniStack external box Mac,Mac external box 35 USB 3.0 eSATA FireWire 800/400.,108.99,0,12995397,NTE,NewerTech
166,OWC0037,"OWC Mercury Elite Pro Mini aluminum box 25 ""FW800 / USB2 / eSATA",outer case 25 inch SATA eSATA / FW800 / FW400 / USB 2.0.,69.99,0,12995397,OWC,OWC
271,NTE0025,NewerTech Voyager Q HDD Dock FW800 / 400 / USB3.0 / eSATA,Dock disc 25 inch and 35 inch FW800 / 400 / USB3.0 / eSATA.,108.99,0,12995397,NTE,NewerTech
272,NTE0026,NewerTech Voyager S3 Dock HDD USB3.0 / Sata,Dock disc 25 inches and 35 inches with USB3.0 / eSATA.,60.99,1,12995397,NTE,NewerTech
312,LMP0011,External Slim Case for SuperDrive iMac and Mac mini,external enclosure iMac SuperDrive and Mac Mini.,35.00,0,12995397,LMP,LMP
367,HGD0018,"Henge Docks Docking Station MacBook Air 11 """,Dock with multiple functions and USB 3.0 for MacBook Air 11-inch,74.99,0,12995397,HGD,Henge Docks
413,NTE0049,NewerTech miniStack MAX + DVD recorder / CD,Housing for Mac Mini with recorder and card reader.,235.99,1,12995397,NTE,NewerTech
414,NTE0050,NewerTech miniStack MAX + Recorder BLURAY / DVD / CD,Housing for Mac Mini with DVD and Bluray DVD recorder and card reader.,337.99,0,12995397,NTE,NewerTech
468,NTE0053,NewerTech miniStack Classic Mac external box,Mac external box 35 FireWire 800 USB 2.0.,64.99,0,12995397,NTE,NewerTech
594,WDT0206,WD My Cloud 4TB Gigabit Ethernet USB 3.0,WD external hard drive with 4TB cloud storage.,209.99,0,12995397,WDT,Western Digital
642,SNN0027,Sonnet Echo Express III-D Chassis expansion Thunderbolt,Thunderbolt external box card PCIe ExpressCard Mac.,1087.79,0,12995397,SNN,Sonnet
752,SNN0030,Sonnet Echo Express Thunderbolt SEII 2 PCIe expansion chassis,Thunderbolt chassis 2 PCIe expansion cards.,543.29,0,12995397,SNN,Sonnet
756,SNN0032,Sonnet Echo Express III-R 2U Chassis Rack Thunderbolt 2,PCIe expansion chassis for Mac via Thunderbolt.,1208.79,0,12995397,SNN,Sonnet
894,LAN0009,"LandingZone Docking Station 2.0 Pro MacBook Air 11 ""(2012-14)",and Base Station Dock USB 3.0 and Gigabit Ethernet for MacBook Air 11.,209.99,0,12995397,LAN,LandingZone
1219,KAN0036,Kanex Hub 4 USB 3.0 ports,Kanex Hub USB 3.0 Mac and PC 4 port.,59.95,0,12995397,KAN,Kanex
1393,KEN0209,UH4000 Kensington 4-Port USB 3.0 Hub,Hub 4 USB 3.0 ports for Mac and PC.,27.49,0,12995397,KEN,Kensington
1410,KEN0208,Kensington UH4000C Hub 4 port power supply,Mac and PC Hub 4 USB 3.0 ports.,44.99,0,12995397,KEN,Kensington
1663,LMP0016,"LMP DataPort External Enclosure 2.5 ""USB 3.0",external enclosure USB 2.5 inch disks 3.0.,29.99,1,12995397,LMP,LMP
1685,BEL0181,Belkin Thunderbolt Express HD Hub 2,Dock Thunderbolt 2 (10Gbps) 4K resolution video and cable included for Mac and PC,249.99,1,12995397,BEL,Belkin
1788,MAC0102,Macally Hub 3 USB 3.0 ports + Ethernet Plata,Hub 3 USB 3.0 ports with Gigabit Ethernet adapter for Mac and PC.,44.95,1,12995397,MAC,Macally
2071,OWC0144,OWC Thunderbolt 2 Dock USB3 / FW / HDMI / Audio / Ethernet,Dock with Ethernet connection Thunderbolt ultra fast USB 3.0 HDMI and GigaEthernet for Mac.,300.99,1,12995397,OWC,OWC
2121,GTE0049,G-Technology G-Drive USB 3.0 Hard Drive 6TB,6TB external hard drive with USB 3.0 connection for Mac and PC.,215.99,1,12995397,GTE,G-Technology
2180,OWC0145,OWC Thunderbolt 2 Dock Cable,Dock 12 ports Thunderbolt connection and cable 1 meter for Mac.,337.99,1,12995397,OWC,OWC
2187,LAN0014,"LandingZone Docking Station Dock Express MacBook Pro Retina 15 """,Dock with USB 3.0 connection HDMI and Thunderbolt slot Kensington security keys for MacBook Pro Retina 15 inches.,104.99,1,12995397,LAN,LandingZone
2370,SNN0050,Sonnet Echo Express SE Thunderbolt PCIe expansion chassis 2,Thunderbolt chassis 2 PCIe expansion cards.,325.49,0,12995397,SNN,Sonnet
2438,GTE0053,G-Technology G-RAID 4TB USB 3.0 RAID Extraóble,extraóble disk RAID FireWire 800 and USB 3.0 for Mac and PC.,408.99,0,12995397,GTE,G-Technology
3024,WDT0310,Western Digital My Book Pro 6TB Thunderbolt 2,6TB external hard drive and dual Thunderbolt 2 port.,659.99,1,12995397,WDT,Western Digital
3113,TRA0040,"Transcend StoreJet outer box 25 ""Aluminum",external enclosure USB 2.5 inch disks 3.0.,14.99,0,12995397,TRA,Trascend
3299,OTR0039-A,Open - External Slim Case for SuperDrive MacBook / MacBook Pro,Reconditioned external box SuperDrive for MacBook and MacBook Pro,35.00,0,12995397,OTR,Startech
3338,KAN0049,Kanex Thunderbolt Docking Station 2.0,Dock with Ethernet and Thunderbolt ultra fast USB 3.0 connection.,229.99,0,12995397,KAN,Kanex
3551,OWC0160,"OWC Dock Thunderbolt station 2 with 2 drive bays 25 ""and 35""",Dock for discs 25 inch and 35 inch Dual Thunderbolt 2 and USB 3.0.,338.99,0,12995397,OWC,OWC
3960,MAC0122,"Macally USB 3.0 External Enclosure 2.5 ""SATA Plata",Aluminum HDD external case 2.5 USB 3.0 for Mac and PC inches.,29.95,0,12995397,MAC,Macally
3967,MAC0123,"Macally USB 3.0 External Enclosure 3.5 ""SATA Plata",aluminum outer box to protect SATA HDD 35 inches for Mac and PC,44.95,1,12995397,MAC,Macally
4205,WDT0325,Western Digital My Book Duo 6TB USB 3.0,6TB external hard drive with two hard drives and USB 3.0 WD RED high-speed ports for Mac and PC.,329.99,0,12995397,WDT,Western Digital
4297,WDT0324,Western Digital My Book Pro 16TB Thunderbolt 2,16TB external hard drive and dual Thunderbolt 2 port,1149.99,0,12995397,WDT,Western Digital
4549,KEN0242,SD3500v Kensington Docking USB 3.0 / DVI / HDMI / Ethernet,Dock with multiple USB connections 3.0 DVI / HDMI / DVI and Ethernet adapters VGA / HDMI for Mac and PC,194.99,0,12995397,KEN,Kensington
4739,KEN0228,Kensington Docking Station USB 3.0 to VGA / HDMI / DVI,Dock with 6 USB ports and dual video connector for Mac and PC,164.99,0,12995397,KEN,Kensington
4740,MAC0126,U3HUBA Macally Hub USB 3.0 4 port,Hub 4 ports USB 3.0 High Speed ​​for Mac and PC,34.95,1,12995397,MAC,Macally
4818,LMP0021,"LMP DataStore External Enclosure 35 ""USB 3.0 Aluminum",external enclosure USB 3.0 discs 3.5 inches.,54.99,1,12995397,LMP,LMP
4929,LAC0194,LaCie 2big Quadra 8TB RAID FW800 USB 3.0,8TB external hard drive USB 3.0 speed and ultra-fast RAID system for Mac and PC,469.00,0,12995397,LAC,LaCie
4940,GTE0068,G-Technology G-Drive USB 3.0 Hard Drive 8TB,8TB external hard drive with USB 3.0 connection for Mac and PC,319.99,0,12995397,GTE,G-Technology
4953,GTE0078,G-Technology 8TB G-RAID Thunderbolt 2 USB 3.0 Extraóble Plata,8TB RAID disk with 2 bays and removable disks Thunderbolt connection 2 and USB 3.0 for Mac and PC,683.99,0,12995397,GTE,G-Technology
5318,HGD0001-A,"Open - Henge Docks Docking Station MacBook Pro 13 """,Dock and open support with multiple connections for MacBook Pro 13-inch,69.99,0,12995397,HGD,Henge Docks
5469,OWC0190,25 or OWC Dual Dock Station USB 3.1 HDD 35,Disk dock 25-inch and 35-inch USB 3.1 cable incluódo Mac and PC,96.99,1,12995397,OWC,OWC
5477,OWC0201,OWC USB-C Dock USB 3.1 / HDMI / Audio / GigaEthernet Rose Gold,Dock USB-C multiple connections and SD reader Macbook.,217.99,0,12995397,OWC,OWC
5481,DRB0019-A,Open - Dr. Bott SmartDock Universal Dock with USB 3.0 US 230 V,Dock Station with USB cable included for Mac and PC,100.00,0,12995397,DRB,NaN
5855,SAT0018,"Satechi External Case 25 ""Aluminum HDD and SSD USB-C Plata",Outer carton for HDDs and SSD 25 inch format for Mac and PC,44.99,1,12995397,SAT,Satechi
5856,SAT0019,"Satechi External Case 25 ""Aluminum HDD and SSD USB-C Gray Space",Outer carton for HDDs and SSD 25 inch format for Mac and PC,44.99,1,12995397,SAT,Satechi
5858,OWC0214,OWC 3 Dock 13 Thunderbolt USB 3.1 ports / Ethernet / Audio Gray Space,Aluminum Dock with 13 different ports includes 2 Thunderbolt ports 3 (40Gb / s) and 05m cable for Mac and PC,362.99,1,12995397,OWC,OWC
5859,OWC0215,OWC 3 Dock 13 Thunderbolt ports / USB 3.1 / Ethernet / Audio Silver,Aluminum Dock with 13 different ports includes 3-port Thunderbolt (40Gb / s) and 0.5m cable for Mac and PC,362.99,1,12995397,OWC,OWC
6101,NTE0111,"NewerTech antistatic StoraDrive Disc Box 35 """,antistatic storage box 2 hard drives 35,17.99,1,12995397,NTE,NewerTech
6298,PRO0026,Promise Pegasus R4 Edition 3 Symply 12TB Hard Disk Thunderbolt 3,massive external storage 12TB (4x3TB) with Thunderbolt 3 Connection for Mac and PC,1881.99,0,12995397,PRO,Promise
6486,SNN0022,Sonnet Echo Express SE Thunderbolt PCIe box,Thunderbolt Expansion Chassis PCIe Cards,482.79,0,12995397,SNN,Sonnet
6885,SNN0056,Sonnet Echo Express Thunderbolt SE1 3 Chassis PCIe expansion,Thunderbolt Expansion Chassis 3 for PCIe Cards,301.29,0,12995397,SNN,Sonnet
6886,SNN0055,Sonnet Echo Express Thunderbolt SEL 3 Chassis PCIe expansion,Thunderbolt expansion chassis 3 for low profile PCIe cards,301.29,0,12995397,SNN,Sonnet
6909,SNN0053,Twin Sonnet Thunderbolt Adapter 10G Chassis 3 to 10 Gigabit Ethernet,10Gb Ethernet adapter chassis Thunderbolt 3 for Mac and PC,785.29,0,12995397,SNN,Sonnet
6911,SNN0054,Sonnet Twin 10G SFP + 10G SFP + adapter chassis Thunderbolt 3,Chassis fiber optic adapter Thunderbolt 3 for Mac and PC,785.29,0,12995397,SNN,Sonnet
6991,LEX0044,Workflow Lexar Professional USB 3.0 Dock HR1,Dock box 4 bay compatible with USB 3.0 and SSD Lexar UH1 UR2 External Mac and PC,84.99,0,12995397,LEX,Lexar
7111,AKI0013,Akitio Neutrino U3.1 USB external box-C,outer case 25 inch disc USB-C (10 Gbps) Mac and PC connection,66.00,0,12995397,AKI,Akitio
7175,AKI0014,Akitio Neutrino Thunder outer box D3 Thunderbolt,External connection box with Thunderbolt and USB 3.0 for 25 inch discs Mac and PC,242.00,0,12995397,AKI,Akitio
7192,AKI0018,"Akitio Thunder3 QUAD Mini External Box 25 ""Thunderbolt 3",external enclosure 25 inch discs connection Thunderbolt 3 (40 Gbps) and DisplayPort for Mac and PC,541.00,1,12995397,AKI,Akitio
7193,AKI0019,Akitio Thunder2 QUAD Case External Thunderbolt 2,Disk outer box 25 inch and 35 inch Thunderbolt 2 (20 Gbps) connection for Mac and PC,468.00,0,12995397,AKI,Akitio
7194,AKI0020,Akitio Thunder2 QUAD Box Mini External thunderbolt2,external enclosure 25 inch discs Thunderbolt 2 (20 Gbps) connection for Mac and PC,393.00,0,12995397,AKI,Akitio
7214,AKI0022,Box Thunder2 Akitio PCIe Thunderbolt 2,Thunderbolt chassis 2 PCI Express expansion cards,319.00,0,12995397,AKI,Akitio
7215,AKI0021,Akitio NODE Case External Thunderbolt PCIe Graphics Card 3,Thunderbolt expansion unit 3 for PCI Express Graphics Cards,399.99,1,12995397,AKI,Akitio
7654,SNN0062,Sonnet eGFX Breakaway Box 550W PCIe Thunderbolt Expansion Box 3,Expansion box for graphics cards and PCIe cards with 550W power,422.29,1,12995397,SNN,Sonnet
7655,SNN0063,Sonnet eGFX Breakaway Box 350W PCIe Thunderbolt Expansion Box 3,Expansion box for graphics cards and PCIe cards with 350W power,361.79,0,12995397,SNN,Sonnet
7657,SNN0068,Sonnet Echo Express PCIe Thunderbolt Expansion Box SEIII 3,Thunderbolt expansion box 3 for PCIe,603.79,0,12995397,SNN,Sonnet
7658,SNN0066,Sonnet Echo Express III-D Box PCIe Thunderbolt 3,Thunderbolt expansion box 3 for PCIe cards with 3 slots,1087.79,0,12995397,SNN,Sonnet
7724,SNN0067,Sonnet Echo Express III-R Box Rack PCIe Thunderbolt 3,Expansion box through the PCIe bus format Thunderbolt 3 rack for Mac,1208.79,0,12995397,SNN,Sonnet
7777,OWC0230,OWC USB-Dock C-10 80W power ports Oro,Aluminum Hub with 10 different ports include 2 USB-C ports and 0.5m cable for Mac and PC,217.99,1,12995397,OWC,OWC
7778,OWC0231,OWC USB Dock-C 10-port power 80W Rose Gold,Aluminum Hub with 10 different ports include 2 USB-C ports and 0.5m cable for Mac and PC,217.99,0,12995397,OWC,OWC
7779,OWC0232,OWC USB Dock-C 10-port power 80W Gray Space,Aluminum Hub with 10 different ports include 2 USB-C ports and 0.5m cable for Mac and PC,217.99,1,12995397,OWC,OWC
7780,OWC0233,OWC USB Dock-C 10-port power 80W Plata,Aluminum Hub with 10 different ports include 2 USB-C ports and 0.5m cable for Mac and PC,217.99,1,12995397,OWC,OWC
8038,LAC0235,LaCie 2big Quadra USB 3.0 FW800 RAID 12TB,12TB External Hard Drive USB 3.0 speed and ultra-fast RAID system for Mac and PC,609.00,0,12995397,LAC,LaCie
8088,AKI0015-A,Open - Akitio NODE Case External Thunderbolt PCIe Graphics Card 3,Thunderbolt expansion unit 3 for PCI Express Graphics Cards,399.99,0,12995397,AKI,Akitio
8322,OWC0234,OWC USB Travel Dock-C / USB 3.1 / HDMI / SD Card Gold,Dock USB-C multiple connections and SD reader Macbook.,66.99,0,12995397,OWC,OWC
8324,OWC0235,OWC USB Travel Dock-C / USB 3.1 / HDMI / SD Cards Rose Gold,Dock USB-C multiple connections and SD reader Macbook.,66.99,0,12995397,OWC,OWC
8326,OWC0236,OWC USB Travel Dock-C / USB 3.1 / HDMI / SD Card Gray Space,Dock USB-C multiple connections and SD reader Macbook.,66.99,1,12995397,OWC,OWC
8327,OWC0237,OWC USB Travel Dock-C / USB 3.1 / HDMI / SD Card Silver,Dock USB-C multiple connections and SD reader Macbook.,66.99,1,12995397,OWC,OWC
8775,BEL0306,Belkin Thunderbolt Express HD Dock 3,Thunderbolt Dock 3 (40Gbps) 4K resolution video and cable included for Mac and PC,349.99,0,12995397,BEL,Belkin
8964,AKI0016-A,Open - Akitio Thunder2 Thunderbolt PCIe expansion box 2,2 Thunderbolt expansion chassis with packaging open PCI Express Cards,319.00,0,12995397,AKI,Akitio
9203,SNN0069,Sonnet eGFX Breakaway Puck Radeon RX560 Thunderbolt 3,Box Portable expansion graphics cards with Radeon RX560 included,699.99,0,12995397,SNN,Sonnet
9204,SNN0070,Sonnet eGFX Breakaway Puck Radeon RX570 Thunderbolt 3,Box Portable expansion graphics cards with Radeon RX570 included,899.99,0,12995397,SNN,Sonnet
9241,AKI0031,Akitio Thunder3 QUAD X Case External Thunderbolt 3,Disk outer box 25 inch and 35 inch Thunderbolt 3 connection (40 Gbps) for Mac and PC,537.00,1,12995397,AKI,Akitio
9250,OWC0268,"OWC Express External Enclosure 25 ""USB 3.0 Plata",Outer carton for HDDs and SSD 25 inch format for Mac and PC,36.99,1,12995397,OWC,OWC
9251,OWC0269,"OWC Express External Enclosure 25 ""USB 3.0 White",Outer carton for HDDs and SSD 25 inch format for Mac and PC,36.99,1,12995397,OWC,OWC
9252,OWC0270,OWC Express USB 3.0 External Enclosure 25 Black,Outer carton for HDDs and SSD 25 inch format for Mac and PC,36.99,1,12995397,OWC,OWC
9545,SNN0044-A,Open - Sonnet Echo Express SE Thunderbolt PCIe expansion chassis 2,Refurbished chassis Thunderbolt 2 PCIe expansion cards.,325.49,0,12995397,SNN,Sonnet
9592,AKI0032,Akitio NODE Pro PCIe Card Thunderbolt External Box 3,Thunderbolt expansion unit 3 for PCI Express Cards,465.00,1,12995397,AKI,Akitio
9709,SAT0012-A,"Open - Satechi External Case 25 ""Aluminum HDD and SSD USB-C Plata",External box reconditioned for HDDs and SSD 25 inch format for Mac and PC,44.99,0,12995397,SAT,Satechi

In [33]:
pbm.loc[pbm["sku"] == "OTR0045", :]

,sku,name,desc,price,in_stock,type,short,long
82,OTR0045,External Slim Case for SuperDrive MacBook / MacBook Pro,External SuperDrive case for MacBook and MacBook Pro.,35.0,1,12995397,OTR,Startech

In [34]:
pbm.loc[pbm["sku"] == "STA0045", :]

,sku,name,desc,price,in_stock,type,short,long
6104,STA0045,Startech charging cable 2m Thunderbolt 3 20Gb / s (compatible USB-C),Cable length 2 meters connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,49.99,1,1325,STA,Startech

In [35]:
brands_df.loc[brands_df["short"] == "XSO"]

Empty DataFrame
Columns: [short, long]
Index: []

In [38]:
brands_df.to_csv("brands_cleaned_phase_1.csv", index=False)